inclavare-containers/inclavare-containers

rune/libenclave/internal/runtime/pal/spec.md
The prototype declaration of pal_init() is wrong, this is a
copy-paste error, this patch fixes it.
=> pal: Fix function declaration error in PAL API Specification

rune/libenclave/runelet.go
If the returned error is empty, don't raise an error in any way.
=> rune/libenclave: Sanity check the returned error of rune exec

rune/libcontainer/container_linux.go, rune/libcontainer/factory_linux.go, rune/libcontainer/init_linux.go, rune/libcontainer/nsenter/loader.c, rune/libcontainer/nsenter/loader.go, rune/libcontainer/process.go, rune/libcontainer/setns_init_linux.go, rune/libcontainer/standard_init_linux.go, rune/libenclave/bootstrap.go, rune/libenclave/internal/runtime/enclave_runtime.go, rune/libenclave/internal/runtime/pal/api_linux.go, rune/libenclave/internal/runtime/pal/pal.go, rune/libenclave/internal/runtime/pal/pal_linux.go, rune/libenclave/runelet.go, rune/utils_linux.go
1. If rune create is running in detach mode, then runelet does not use logpipe.
2. Use unified pal api interface.
=> Unified palapi

rune/libcontainer/nsenter/loader.c
If rune is used as runc, PAL path will not be specified, runc logic
should be followed.
=> rune/nsenter: Compatible with runc when PAL path is not specified

rune/libcontainer/container_linux.go, rune/libcontainer/factory_linux.go, rune/libcontainer/init_linux.go, rune/libcontainer/process.go, rune/libcontainer/setns_init_linux.go, rune/libcontainer/standard_init_linux.go, rune/libenclave/bootstrap.go, rune/libenclave/runelet.go, rune/libenclave/utils.go, rune/utils_linux.go
Because there is no re-exec operation, there is no need to use
environment variables to pass parameters between bootstrap and
runelet, use global variables instead of environment variables.
=> rune/libenclave: Optimize the way of passing parameters

rune/libenclave/internal/runtime/pal/skeleton/Makefile, rune/libenclave/internal/runtime/pal/skeleton/defines.h, rune/libenclave/internal/runtime/pal/skeleton/encl.c, rune/libenclave/internal/runtime/pal/skeleton/encl_bootstrap.S, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/sgx_call.S, rune/libenclave/internal/runtime/pal/skeleton/sgx_call.h
In order to implement more ecall functions, it is necessary to
implement a general sgx entry point with ecall number to
corresponding ecall handler.
=> rune/libenclave: Implement the general sgx entry point for skeleton

rune/libcontainer/nsenter/loader.c
The current LD_LIBRARY_PATH value is only the default value of
centos, more OS environment should be compatible.
=> rune/libcontainer: dlopen LD_LIBRARY_PATH supports more OS

rune/libcontainer/container_linux.go, rune/libcontainer/nsenter/loader.c
It is found in the experiment that LD_LIBRARY_PATH must be set
before the process starts, which may be caused by the internal
cache. Therefore, the LD_LIBRARY_PATH environment setting is
moved to before bootstrap starts.
=> rune/libcontainer: Fix LD_LIBRARY_PATH invalid in dlopen()

rune/libcontainer/container_linux.go, rune/libcontainer/nsenter/loader.c, rune/libcontainer/nsenter/nsexec.c
Instead of inheriting LD_LIBRARY_PATH by bootstrap, make it available
only for boostrap's child process.
=> rune/libenclave: Fix processing LD_LIBRARY_PATH #2

rune/Makefile
make statically dependent PROTOS to *.pb.go files.
=> rune: fix statically make error.

rune/libcontainer/specconv/example.go, rune/libcontainer/specconv/spec_linux.go
The minor device number should not be hard-coded with 58 for
SGX enclave devices.
=> rune/libcontainer: Fix implicitly mounting enclave device

rune/libcontainer/specconv/example.go, rune/libcontainer/specconv/spec_linux.go
/run is usally a symbol link to /var/run but it is not always true.
=> rune/libcontainer: Mount aesm.socket from /var/run/aesmd/

rune/libcontainer/specconv/example.go
This path doesn't always exist in a container.
=> rune/libcontainer: Fix the path to /run/rune

rune/libcontainer/setns_init_linux.go, rune/libcontainer/standard_init_linux.go
The final error message will be sent back to the parent so there is
no need to log it.
=> rune/libcontainer: Clean up enclave exit path on error

rune/libenclave/intelsgx/device_linux.go
Due to the design of runelet, the Enclave Runtime PAL is loaded
in host but launched in container. The fact that certain libraries
from Intel SGX PSW would use dlopen() to further load libsgx_launch.so,
which means the container has to have it. In  order to ensure all
libraries dependent by Enclave Runtime PAL are completely loaded in
host, preload them prior to switch into container.
=> rune/libenclave: Preload libsgx_launch.so

Makefile, rune/Makefile
1. add global Makefile for all components. 
2. add make uninstall for rune/Makefile.  
=> rune && runectl && shim: Add global Makefile

rune/libenclave/internal/runtime/pal/skeleton/README.md
=> rune/libenclave: Fix spelling mistakes in skeleton README.md.

shim/runtime/carrier/constants/constants.go, shim/runtime/carrier/occlum/occlum.go, shim/runtime/v2/rune/v2/rune.go
fix the issue that /dev is mounted abnormally in the scratch image, and delete the code that mount directories in config.json on the rootfs.
=> fix the issue that /dev is mounted abnormally in the scratch image

rune/libenclave/intelsgx/aesmd.go, rune/libenclave/intelsgx/proto/aesm-service.proto
If not distinguish default value and missing value in pb3, pb3 will drop default value
in protobuf requests.
=> rune/libenclave: using `oneof` to distinguish default value and missing value in pb3.

rune/libcontainer/specconv/spec_linux.go
Support to automatically mount the /dev/gsgx driver to inclavare containers.
=> rune/libcontainer: Generate Enclave Device /dev/gsgx for graphene-sgx LibOS.

Makefile, rune/Makefile, rune/dist/Makefile, rune/dist/centos/rune.spec, shim/Makefile, shim/dist/Makefile, shim/dist/centos/shim-rune.spec
1. Add Global make rpm for building rpms of rune and shim.
2. Add rpm specs  for rune/dist/centos and shim/dist/centos.
Signed-off-by: Chunmei Xu <xuchunmei@linux.alibaba.com>
Signed-off-by: Zhiguang Jia <Zhiguang.Jia@linux.alibaba.com>
=> rune && shim: Add centos rpms spec.

rune/libcontainer/configs/enclave.go, rune/libcontainer/process_linux.go, rune/libcontainer/specconv/spec_linux.go, rune/libenclave/configs/config.go
1. Add optional remote attestation annotation fields in config.json.
2. Pass remote attestation configs to Enclave Containers.
=> rune: Add optional remote attestation annotation fields in config.json.

rune/Makefile, rune/libenclave/intelsgx/aesmd.go, runectl/vendor/github.com/opencontainers/runc/libenclave/intelsgx/aesmd.go
1. rune: Add libenclave/attestation/proto in Makefile.
2. rune/libenclave: Drop invalid fields in Quote to avoid invalid Attestation Evidence Payload error(ErrorCode: 400).
3. runectl: Minor fixes to sync up with the attestation package from rune/libenclave.
=> rune && runectl: Minor fixes in the attestation package.

rune/libcontainer/configs/enclave.go, rune/libcontainer/configs/validate/validator.go, rune/libcontainer/process_linux.go, rune/libcontainer/specconv/spec_linux.go, rune/libenclave/attestation/sgx/attest.go, rune/libenclave/configs/config.go, rune/libenclave/intelsgx/arch.go
1. transfer config.RaType from string type to uint32 type.
2. rename config.RaEpidQuoteType as config.RaEpidIsLinkable.
3. set config.RaEpidIsLinkable type as uint32.
=> rune: revise remote attestation optional configurations type.

README.md
=> docs: fix the url error of terminology doc in README.md.

shim/config/config.go, shim/runtime/carrier/constants/constants.go, shim/runtime/carrier/occlum/config.go, shim/runtime/carrier/occlum/occlum.go, shim/runtime/signature/client/client.go, shim/runtime/signature/server/api/api.go, shim/runtime/signature/server/api/handler.go, shim/runtime/signature/server/api/server.go, shim/runtime/v2/rune/v2/rune.go
1. Make the shim-rune adapt to occlum 0.14
2. Base64 encode the signatrue when sending signature body from server and base64 decode signature when retriving signature  bodyfrom client
3. Update the variable names of occlum process settings
=> make the shim-rune adapt to occlum 0.14

rune/attest.go, rune/libcontainer/nsenter/enclave.c, rune/libcontainer/nsenter/loader.go, rune/libenclave/agent.go, rune/libenclave/internal/runtime/core/core.go, rune/libenclave/internal/runtime/enclave_runtime.go, rune/libenclave/internal/runtime/pal/api_linux_v1.go, rune/libenclave/internal/runtime/pal/api_linux_v3.go, rune/libenclave/internal/runtime/pal/pal_linux.go, rune/libenclave/proto/agent-service.proto, rune/libenclave/runelet.go, rune/main.go, rune/utils_linux.go, sgx-tools/gen-quote.go
1. Add GetSgxReport PAL API.
2. Support to IAS remote attestation when Enclave Runtime started.
3. Support `rune attest` command.
=> rune: support to IAS remote attestation when enclave runtime started and rune attest command.

patch/no-sgx-flc/0001-psw-Support-SGX1-machine-with-SGX-in-tree-driver.patch, patch/no-sgx-flc/0001-sgx-Support-SGX1-machine-even-without-FLC-support.patch, patch/no-sgx-flc/README.md
There are still non-trivial number of systems without FLC support.
=> patch: Add no-sgx-flc patchset

README.md
For demonstration purpose, the reference container images are
availbale. Currently, web application demos based on OpenJDK 11
and Golang are provided.
=> README: Add the contents about reference container image

rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
In the GNU C Library, "major" is defined by <sys/sysmacros.h>
starting from glibc-2.25, the macros major and minor are only available in <sys/sysmacros.h>.
This fix is for historical compatibility.
=> rune/libenclave/skeleton: 

rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/sgx_call.S
This argument is used to test whether enclave share mapping between
parent and child process is usable.
=> rune/libenclave/skeleton: Support fork-test argument

rune/libenclave/internal/runtime/pal/skeleton/Makefile, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v2.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.h
- v2 implementation in a separate file.
- v2 support SGX in-tree driver, don't support SGX oot driver.
=> rune/libenclave/skeleton: Support pal api v2 with SGX in-tree driver

rune/libenclave/internal/runtime/pal/skeleton/README.md
using liberpal-skeleton-v${SKELETON_PAL_VERSION}.so to replace
liberpal-skeleton.so in README.md of skeleton.
=> docs: update skeleton README.md to support different PAL versions.

rune/.gitignore, rune/Makefile, rune/libcontainer/specconv/example.go, rune/libenclave/internal/runtime/pal/skeleton/README.md
- Use liberpal-skeleton-v${SKELETON_PAL_VERSION}.so to replace liberpal-skeleton.so in README.
- Use liberpal-skeleton-v1.so to replace liberpal-skeleton.so in rune/libcontainer/specconv/example.go
- Use liberpal-skeleton*.so to repalce liberpal-skeleton.so in rune/Makefile and .gitignore
=> rune: Update the version of liberpal-skeleton.so in rune

rune/libenclave/internal/runtime/pal/skeleton/.gitignore, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v2.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.h
1. sink the implementation of PAL V2 APIs: Move the implementation of skeleton PAL V2 APIs from liberpal-skeleton-v2.c to liberpal-skeleton.c
2. ignore *.so, *.token and Dockerfile.
3. add sanity check in skeleton PAL APIs.
4. support the `debug` arg.
5. support PAL API V3: support pal_get_local_report API and remote attestation at bootstrap, add skeleton_remote_attestation_with_rune.md.
=> rune/libenclave/skeleton: refactor pal api v2 and add pal api v3.

rune/libenclave/agent.go, rune/libenclave/attestation/check.go, rune/libenclave/attestation/nonce.go, rune/libenclave/attestation/registry.go, rune/libenclave/attestation/service.go, rune/libenclave/attestation/sgx/attest.go, rune/libenclave/attestation/sgx/ias/api.go, rune/libenclave/attestation/sgx/ias/ias.go, rune/libenclave/attestation/utils.go, rune/libenclave/attestation/verify.go, rune/libenclave/configs/config.go, rune/libenclave/init.go, rune/libenclave/intelsgx/aesmd.go, rune/libenclave/intelsgx/arch.go, rune/libenclave/intelsgx/cpuid.go, rune/libenclave/intelsgx/device_linux.go, rune/libenclave/intelsgx/epc.go, rune/libenclave/intelsgx/launch_control.go, rune/libenclave/intelsgx/secs.go, rune/libenclave/internal/runtime/core/core.go, rune/libenclave/internal/runtime/enclave_runtime.go, rune/libenclave/internal/runtime/pal/api_linux_v1.go, rune/libenclave/internal/runtime/pal/api_linux_v2.go, rune/libenclave/internal/runtime/pal/api_linux_v3.go, rune/libenclave/internal/runtime/pal/pal.go, rune/libenclave/internal/runtime/pal/pal_linux.go, rune/libenclave/runelet.go, rune/libenclave/sync.go, rune/libenclave/utils.go
Change import paths from "github.com/opencontainers/runc" to "github.com/inclavare-containers/rune"
=> rune/libenclave: Change import paths to "github.com/inclavare-containers/rune"

rune/libenclave/internal/runtime/enclave_runtime.go, rune/libenclave/internal/runtime/pal/pal_linux.go
Load function has become unnecessary in the rune design. We implement the logic of Load and getPalApiVersion directly in runtime.Init().
=> rune/libenclave: Remove the implementation of runtime.Load()

rune/libenclave/internal/runtime/pal/skeleton/skeleton_remote_attestation_with_rune.md
Only `liberpal-skeleton-v3.so` supports `rune attest` command.
=> docs: Configure enclave.runtime.path as liberpal-skeleton-v3.so in skeleton_remote_attestation_with_rune.md.

rune/libenclave/intelsgx/device_linux.go
Change libsgx_launch.so to libsgx_launch.so.1 in preloadSgxPswLib function
Signed-off-by: Shirong Hao<shirong@linux.alibaba.com>
=> rune/libenclave: Fix the name of PSW library libsgx_launch.so

shim/runtime/v2/rune/v2/rune.go
If not set RuneCarrier(such as Pods), the getCarrierkind should return
<true, rune.Empty, nil>.
=> shim/runtime/v2/rune/v2: Fix the return value error of getCarrierKind

rune/libenclave/internal/runtime/pal/spec_v2.md
=> rune/libenclave: Supplement the missing return value description information of enclave runtime pal API v2 spec

rune/libenclave/internal/runtime/pal/skeleton/Makefile, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/sgx.h, rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c, rune/libenclave/internal/runtime/pal/skeleton/sgxutils.c
Xfrm needs support the same xsave feature in encalve as in OS.
By cpuid, it can get the same value between xfrm and xcr0.
Reviewed-by: Jia Zhang <zhang.jia@linux.alibaba.com>
=> Xfrm should be a subset of xcr0 in different machine

shim/runtime/v2/rune/v2/service.go
1. Store inclavare-containers configuration.
2. Clean up unused remote attestation codes in service.Create function.
=> shim/runtime: Store inclavare-containers configuration

ra-tls/sgx-ra-tls/ra_tls_options.c.sh
ra-tls: In python, range paramter should use int type instead of float. And remove SGX_UNLINKABLE_SIGNATURE hardcode replacing with variant quote_type.
=> fix an error and remove a hardcode. 

rune/libenclave/internal/runtime/pal/skeleton/README.md
- The code of liberpal-skeleton is constantly being updated, it may not be compatible with the previous images.
Signed-off-by: Shirong Hao shirong@linux.alibaba.com
=> rune/libenclave/skeleton: Remove skeleton image

rune/libenclave/internal/runtime/pal/skeleton/skeleton_remote_attestation_with_rune.md
The --debug option of rune should be enabled to show IAS report when RA.
=> rune/libenclave/skeleton: Enable the --debug option of rune in skeleton RA

sgx-tools/README.md, sgx-tools/gen-quote.go, sgx-tools/get-ias-report.go, sgx-tools/go.mod, sgx-tools/main.go, sgx-tools/vendor/github.com/opencontainers/runc/libenclave/attestation/sgx/attest.go, sgx-tools/vendor/modules.txt
1. Add the `get-ias-report` command to get RA report from IAS according to the given quote file.
2. Modify the usage description of gen-quote command.
=> sgx-tools: Add the get-ias-report command to get RA report from IAS

rune/libenclave/internal/runtime/pal/spec_v2.md
In enclave runtime PAL v2, the API of PAL version is named as pal_get_version
rather than pal_version.
=> rune/libenclave/pal: fix the PAL version API description error in spec_v2.md

ra-tls/README.md
Create the /run/rune directory before running ra-tls-server.
=> ra-tls/README.md: Solve the problem of running ra-tls-server failed if the /run/rune directory doesn't exist

README.md, rune/libenclave/internal/runtime/pal/spec.md, rune/libenclave/internal/runtime/pal/spec_v1.md, rune/libenclave/internal/runtime/pal/spec_v2.md
Add each PAL API vesion information and the relationship between
`rune` subcommands and PAL APIs in the total enclave PAL API spec.
=> rune/libenclave/pal: add a total enclave runtime PAL API spec

rune/libenclave/internal/runtime/pal/pal_linux.go
This reverts commit 196cf5ad4180bf1f9981f1523833f6de47760e7b.
=> revert "rune/libenclave: Work around nanosleep() issue"

rune/libenclave/container_linux.go, rune/libenclave/factory_linux.go, rune/libenclave/init_linux.go, rune/libenclave/intelsgx/preload/device_linux.go, rune/libenclave/internal/runtime/pal/loader.go
This bug fix the error message of "Failed to load library" when running rune exec.
=> rune/libenclave: do not load psw and pal dynamic library when rune exec

rune/libenclave/intelsgx/aesmd.go
=> rune/libenclave: fix the check error of quote length in intelsgx.GetQuote

patch/no-sgx-flc/0001-SGX-DCAP-Linux-Driver-Support-SGX1-machine-even-without-FLC-s.patch, patch/no-sgx-flc/README.md
1. Enable non-trivial SGX 1 machines with SGX DCAP driver.
2. Update the URL of the v33 in-tree Linux SGX driver.
=> patch/no-sgx-flc: add the SGX DCAP linux driver patch and update README.md.

patch/no-sgx-flc/README.md
=> patch/no-sgx-flc: note `no-sgx-flc` feature is not working with `Occlum` in README.md

README.md, rune/Makefile, rune/README.md, rune/libenclave/internal/runtime/pal/skeleton/README.md
=> rune: install rune to /usr/local/bin instead of /usr/local/sbin

rune/spec.go
=> rune: delete read only attribute of rootfs in `config.json` file generated by command `rune spec`

rune/libenclave/internal/runtime/pal/spec.md
rune run subcommand calls the pal_destroy API while rune create and start can't
call the pal_destroy API because they run in the detach mode.
=> rune/libenclave/pal: update the relationship between rune and the pal_destroy API

rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v1.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v2.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v3.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.h
pal_destroy API is not consistent with __pal_destory.It will fix this issue.
=> skeleton: fix a typo issue.

README.md, docs/design/terminology.md, rune/README.md, rune/docs/pal_programming_guide.md
The PAL interface is implemented in WAMR.
This patch provides brief guides for uses and developers to run
WASM app in WAMR with SGX by rune.
Signed-off-by: Le Yao <le.yao@intel.com>
=> Integrate WAMR as an enclave runtime for rune

rune/spec.go
=> rune: remove "skeleton" from args returned by rune spec

rune/libenclave/internal/runtime/pal/skeleton/README.md, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
This parameter can be used to measure the overhead of enclave launch time.
Fixes: #191
=> rune/skeleton: add a memory size parameter for skeleton

rune/libenclave/internal/runtime/pal/skeleton/README.md, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
=> rune/libenclave/skeleton: use enclave-size parameter and -s option instead of memory-size and -m

epm/dist/deb/debian/postrm, epm/dist/deb/debian/rules, epm/dist/rpm/epm.spec, shim/README-zh_CN.md, shim/README.md, shim/config/config.go, shim/runtime/carrier/occlum/occlum.go, shim/runtime/v2/rune/constants/constants.go, shim/runtime/v2/rune/v2/rune.go
1. add a new configuration field `enclave_runtime.signature_method` for shim-rune, which represents the signature method for enclave.
2. update spec files of epm.
=> shim-rune: add the client signature for shim-rune and update spec files of epm.

docs/create_a_confidential_computing_kubernetes_cluster_with_inclavare_containers.md, epm/dist/deb/debian/postinst
set a higher priority to epm to avoid conflicts with another epm package which reside in `mirrors.cloud.aliyuncs.com` repository.
=> epm: set epm package priority in ubuntu repository

rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
=> rune/libenclave/skeleton: fix a memory leak issue

rune/libenclave/internal/runtime/pal/skeleton/Makefile
=> rune/libenclave/skeleton: clean kvmtool when cleaning skeleton

rune/libenclave/internal/runtime/pal/kvmtool/libvmm.c, rune/libenclave/internal/runtime/pal/loader.go, rune/libenclave/internal/runtime/pal/skeleton/Makefile
Fix the skeleton compilation warning and the problem that dlopen()
fails to load liberpal-skeleton.so v1 and v3.
Fixes: #290
=> rune/skeleton: Fix compilation and dynamic link failure

rune/libenclave/internal/runtime/pal/pal_linux.go, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v3.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.h
EPM feature is only supported by newer than PAL v3. However,
current implementation deems a PAL without EPM configured as
PAL v1. This causes a PAL v3 without EPM configured calls
PAL v1 init().
=> rune/skeleton: fix liberpal-skeleton-v3 crash

rune/libenclave/internal/runtime/pal/skeleton/Makefile
When running skeleton, an error will be showed as "dlerror: /usr/lib/
liberpal-skeleton-v3.so: undefined symbol: bfd_openr"
=> rune/libenclave/skeleton: fix an issue about undefined symbol

CONTRIBUTING.md
It is not necessary to have a blank line before SOB.
=> CONTRIBUTING: update the description about fix line

sgx-tools/dist/deb/debian/changelog, sgx-tools/dist/deb/debian/control, sgx-tools/dist/deb/debian/rules, sgx-tools/dist/rpm/sgx-tools.spec
It's obvious that sgx-tools don't depend on protobuf.
=> sgx-tools/dist: drop unnecessary dependency in rpm and deb

rune/libenclave/check.go, rune/libenclave/configs/config.go, rune/libenclave/init.go, rune/libenclave/jailhouse/device_linux.go
There are more and more non hardware-assisted enclave forms to support.
Jailhouse is one of this kind of enclave, we should support it.
Fixes:#344
=> rune/libenclave: support new enclave type jailhouse

patch/no-sgx-flc/README.md
Running occlum application based on dcap driver and non-flc machine, the patch
0001-SGX-DCAP-Linux-Driver-Support-SGX1-machine-even-without-FLC-s.patch need be applied firstly.
Fixes: #384
=> README.md: occlum can run on non-flc machine with dcap driver

rune/libenclave/internal/runtime/pal/skeleton/README.md, rune/libenclave/internal/runtime/pal/skeleton/arch.h, rune/libenclave/internal/runtime/pal/skeleton/encl.c, rune/libenclave/internal/runtime/pal/skeleton/encl.lds, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
There is no need to add `mmap-size` parameter in config.json file, because skeleton will get the mmap-size value from the metadata area.
Fixes: #296
=> rune/libenclave/skeleton: add max-mmap-size metadata area

.github/workflows/rune_centos_with_docker_and_crictl.yml, .github/workflows/rune_ubuntu_with_docker_and_crictl.yml
We change centos to scratch because the size of scratch image is 0 while
the size of centos is tens of MB, so use the scratch image to replace
centos to speed up docker build in CI/CD. The last and the most important,
centos will no longer be free at the end of 2021.
=> .github/workflows: use the scratch image to replace centos to speed up docker build in CI/CD

rune/libenclave/internal/runtime/pal/skeleton/arch.h, rune/libenclave/internal/runtime/pal/skeleton/encl.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
Since the built environment and runtime environment may be different. It is necessary for users to define the expected value of the processor extension state supported by the target platform at runtime by themselves. The expected value will be stored in the metadata area in enclave images, skeleton will act according.
=> rune/libenclave/skeleton: add xfrm and attribute metadate area

.github/workflows/commit_centos.yml, .github/workflows/commit_ubuntu.yml
We use the pull_request_target hook to enable proper permissions for
pull requests coming from forks.
=> .github/workflows: use pull_request_target instead of pull_request

rune/libenclave/internal/runtime/pal/skeleton/README.md
The socket path /var/run/epm is used by epm service and epm client to transfer socket info
between host and container. The path is mounted during starting container in this implementation.
So it can be removed in config.json.
=> README.md: remove /var/run/epm configuration in config.json explicitly

rune/libenclave/internal/runtime/pal/skeleton/arch.h, rune/libenclave/internal/runtime/pal/skeleton/encl.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c, rune/libenclave/internal/runtime/pal/skeleton/sgxutils.c
User can decide whether to enable null_dereference_protection protection
through the command line in sgxsign tool.
In addition, the user can predefine the value of mmap_min_addr when signing on
a machine with a different vm.mmap_min_addr against runtime.
=> rune/libenclave/skeleton: add null_dereference_protection and mmap_min_addr to metadata area

docs/develop_and_deploy_hello_world_application_in_kubernetes_cluster.md, epm/README.md, epm/dist/deb/debian/postinst, epm/dist/rpm/epm.spec, epm/pkg/epm/bundle-cache-pool/occlum/bundle-cache_test.go, shim/README-zh_CN.md, shim/README.md, shim/conf/config.toml, shim/config/config_test.go, shim/dist/deb/debian/postinst, shim/dist/rpm/shim-rune.spec, shim/runtime/v2/rune/constants/constants.go
=> shim-rune && epm: use /var/run/epm and /var/run/rune to replace /run/epm and /run/rune

.github/workflows/commit_ubuntu.yml
For some components like shim-rune and epm, make package can generate
their configuration files automatically.
=> .github/workflows: use make package to replace make binary on ubuntu CI/CD

rune/libenclave/internal/runtime/pal/skeleton/running_skeleton_with_rune_attest_command.md
=> rune/libenclave/skeleton/README.md: add declaration that not support DCAP driver until now for the rune attest command

rune/dist/deb/debian/changelog, rune/dist/rpm/rune.spec, sgx-tools/dist/deb/debian/changelog, sgx-tools/dist/rpm/sgx-tools.spec
=> rune & sgx-tools: bump the versions of deb and rpm to 0.5.2

rune/init.go
For debug purpose, locating the log file at, e.g,
/run/containerd/io.containerd.runtime.v1.linux/moby/6c1d388b3f1fe157506852a6228769a7e5fb38a7153319a66377e0cd332e1d96/log.json,
is painful especially using docker or any high level container
runtime, so the error is still printed to stderr if --debug
is specified.
=> rune: print the error message when --debug specified

.github/workflows/nightly-centos-sgx1.yml, .github/workflows/nightly-ubuntu-sgx1.yml
When clearing the build environment, kubectl and kubeadm may be
not installed. In this case, the `command not found` error message
should be invisible.
=> CI/CD: mask `command not found` error message

rune/libenclave/internal/runtime/pal/skeleton/sgx_call.S, rune/libenclave/internal/runtime/pal/skeleton/sgx_call.h
sgx_ecall conflicts with libsgx_urts from Intel SGX SDK.
=> rune/skeleton: rename sgx_ecall to sgx_enclave_call

.github/workflows/commit_crictl.yml
Fix dragonwell-web and openjdk-pod may not start within 3s.
=> CI/CD: extend the timeout value when creating pods

.github/workflows/docker/Dockerfile-compile-check-centos8.1, .github/workflows/docker/Dockerfile-compile-check-ubuntu18.04
=> CI/CD: add dcap-related compile dependency in centos8.1 and ubuntu18.04

.github/workflows/commit_skeleton.yml
=> CI/CD: use the rune state command to check container status before doing remote attestation test

.github/workflows/commit_skeleton.yml
=> CI/CD: ingore the error print message when waiting for RA containers running.

.github/workflows/commit_skeleton.yml
If not successfully getting local report, it wouldn't get remote report
successfully any more.
=> CI/CD: adjust the jobs order of get local report and get remote report.

rune/libenclave/internal/runtime/pal/skeleton/arch.h, rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
SGX asks for the fixed exponent value 3.
=> rune/skeleton: add sanity check for exponent

.github/workflows/commit_skeleton.yml
The sgxsign tool may not be able to process some keys,
which leads to EINIT error. We will fix it in the future.
=> CI/CD: workround skeleton occasionally failed problem

.github/workflows/commit_skeleton.yml
We need to kill the RA containers after all rune attest test completing
to recycle resources. Besides, we also need to test whether the rune kill
command is OK or not.
=> CI/CD: use rune kill command to kill remote containers when all rune attest test completing

docs/develop_and_deploy_hello_world_application_in_kubernetes_cluster.md
=> docs/k8s: add the ENCLAVE_RUNTIME_LOGLEVEL and OCCLUM_RELEASE_ENCLAVE environment variable to sync up with rune.

sgx-tools/Makefile
Obviously, there is no proto directory in the sgx-tools repository.
=> sgx-tools/Makefile: delete the non-existent proto dependency.

rune/libenclave/intelsgx/aesmd.go, rune/libenclave/intelsgx/arch.go
intelsgx.quoteTypeEcdsa, intelsgx.quoteTypeEpidLinkable and
intelsgx.quoteTypeEpidLinkable must be public to be able to be imported.
Because they will be used as a cli parameter in sgx-tools and rune
attest, and they also will be used as an env variable and annotation for
the config.json of rune.
=> rune/libenclave/intelsgx: make quote type related constant public

rune/libenclave/epm/cmsg.go, rune/libenclave/epm/epm.go
Sometimes epm client tries to get enclave information from pool, the enclave file
descriptor is not received from epm server in time. It will lead that the enclave
fd as zero is filled into enclave information. So when sgx mmap happens, the wrong enclave
information will be inputed as parameter, it will cause permission denied. To correct
the error, it need sync between recieving and filling real fd value into enclave information.
Fixes: #592
=> rune/libenclave/epm: fix a bug about sgx mmap failure

rune/libenclave/attestation/sgx-epid-challenger.go
=> rune/libenclave/attestation: fix the return error of the sgxEpidChallenger.New function

rune/libenclave/internal/runtime/pal/skeleton/sgx.h, rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c, rune/libenclave/internal/runtime/pal/skeleton/sgxutils.c
The solution for SGX1 platforms is not working for SGX2, thus it is
necessary to make sure the hack is only applicable to SGX1 platforms.
=> rune/skeleton: fix EINIT rc 8 failure on SGX2 platforms

rune/libenclave/attestation/challenger.go, rune/libenclave/attestation/sgx/sgx_challenger/sgx-epid-challenger.go, rune/libenclave/internal/runtime/pal/pal_linux.go
sgx-related codes should be located into rune/libenclave/attestation/sgx
package. More specifically, {sgx-attester-related, sgx-challenger-related,
sgx-verifier-related} should be placed into
rune/libenclave/attestation/{sgx_attester, sgx_challenger, sgx_verifier} packages.
=> rune/libenclave/attestation: move sgx-epid-challenger.go to the sgx/sgx_challenger package

.github/workflows/docker/Dockerfile-compile-check-centos8.1, .github/workflows/docker/Dockerfile-compile-check-ubuntu18.04, .github/workflows/nightly-ubuntu-sgx1.yml, README.md, rune/README.md, rune/dist/deb/debian/control, rune/dist/rpm/rune.spec
1. CI/CD: add the ubuntu and centos compile dependence of verifying SGX DCAP quote.
2. rune/dist/rpm && deb: add the compile dependence for verifying SGX DCAP quote.
3. rune/README.md: add the ubuntu and centos compile dependence of verifying SGX DCAP quote.
4. CI/CD: add libsgx-dcap-quote-verify-dev deb in nightly-ubuntu-sgx1.yml.
=> rune/README.md && rpm && deb && CI/CD: add the compile dependence for verifying SGX DCAP quote

.github/workflows/docker/Dockerfile-ubuntu18.04
`libsgx-header*.deb` is needed by `libsgx-dcap-quote-verify*.deb`. If
`libsgx-dcap-quote-verify*.deb` isn't installed by `apt-get install` but
installed by `dpkg`, we also need to install `libsgx-headers` explicitly.
=> CI/CD: install libsgx-headers*.deb in Dockerfile-ubuntu18.04

rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
q2 is not always 384-byte length. Sometimes it only has 383-byte.
In this case, the valid portion of q2 is reordered reversely for
little endian order, and the remaining portion is filled with zero.
=> skeleton/sgxsign: fix EINIT failure dueto SGX_INVALID_SIGNATURE

.github/workflows/docker/Dockerfile-ubuntu18.04
/usr/include/sgx_attributes.h is a file of the libsgx-headers deb since
sgxsdk 2.12. However, Dockerfile-ubuntu18.04 based on
occlum/occlum:$OCCLUM_VERSION-ubuntu18.04 docker image, and the occlum
ubuntu 18.04 docker image based on a lower version sgxsdk 2.11 which
doesn't have a libsgx-headers deb. So we use the soft link the fix the
error of compiling rune.
=> CI/CD: in the Dockerfile-ubuntu18.04, use soft link instead of installing  libsgx-headers to compile rune

rune/libenclave/attestation/internal/sgx/challenger/challenger-ecdsa.go, rune/libenclave/attestation/internal/sgx/dcap/qvl.go, rune/libenclave/attestation/internal/sgx/ias/ias.go, rune/libenclave/intelsgx/arch.go
1. rune/libenclave/attestation: achieve SGX ECDSA challenger.
2. rune/libenclave/attestation: use the public SubscriptionKeyLength constant rather than redefining a private one.
=> rune/libenclave/attestation: achieve SGX ECDSA challenger

.github/workflows/nightly-centos-sgx1.yml, .github/workflows/nightly-ubuntu-sgx1.yml
change the occlum version from 0.19.0 to 0.20.0 and restart aesmd after installed the shim and epm.
=> shim: change the occlum version and fix the problem that Centos nightly build failed

rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
The to-be-signed SIGSTRUCT can be used to run a remote signing.
=> skeleton/sgxsign: support to save SIGTRUCT for to-be-signed

rune/libenclave/attestation/internal/sgx/dcap/qvl.go, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
If enclave debug is not explicitly disabled, the "debug"
enclave runtime argument will enable enclave debug.
=> skeleton: allow to dynamically enable enclave debug

.github/workflows/docker/Dockerfile-ubuntu18.04
If you want to include <sgx_attributes.h>, you cen use
-I/opt/intel/sgxsdk/include rather than installing libsgx-headers or the
soft link about sgx_attributes.h.
=> CI/CD: drop unnecessary soft link about sgx_attributes.h in Dockerfile-ubuntu18.04

inclavared/app.wolfssl/Makefile, inclavared/stub-enclave.wolfssl/Makefile, ra-tls/elv/Makefile, ra-tls/elv/echo-la.go, ra-tls/elv/ra-tls-client.c
Fix the conditional compilation failure in cgo and advance the
creation of enclave before the TLS handshake.
=> ra-tls/elv: fix failure on la report

ra-tls/Makefile
curl-wolfssl should be marked as "PHONY" to enforce the rule.
=> ra-tls: fix build failure due to missing reconfiguration

ra-tls/sgx-ra-tls/Makefile
ra_tls_options.c is generated by ra_tls_options.c.sh which will use python function
to populate SPID. If python is not installed, the SPID value will be empty. It will
lead to the failure of EPID attestation.
Fixes: #664
=> ra-tls/Makefile: add ra-tls epid compiling dependency check for python

.github/workflows/docker/Dockerfile-compile-check-centos8.1
=> CI/CD: use yum to replace rpm to install the sgxsdk and dcap in the compile-check images

.github/workflows/commit_skeleton_ex.yml
Split commit skeleton test into two containers:
- rune_dev container: simulate development environment, used to make
inclavare containers rpm or deb packages and build the app images needed for testing.
- test container: based on ubuntu18.04 or centos 8.2, used to install
inclavare containers rpm or deb packages and test the app images.
=> CI/CD: both enhance commit skeleton test in ubuntu18.04 and centos 8.2 of SGX2

.github/workflows/commit_epm_ex.yml
Split commit epm test into two containers:
- rune_dev container: simulate development environment, used to make
inclavare containers rpm or deb packages and build the app images
needed for testing.
- test container: based on ubuntu18.04 or centos 8.2, used to install
inclavare containers rpm or deb packages and test the app images.
=> CI/CD: both enhance commit epm test in ubuntu 18.04 and centos 8.2 of SGX2

.github/workflows/commit_crictl.yml, .github/workflows/commit_epm.yml, .github/workflows/commit_occlum.yml, .github/workflows/commit_shelter.yml, .github/workflows/commit_skeleton.yml, .github/workflows/docker/Dockerfile-centos8.2, .github/workflows/docker/Dockerfile-ubuntu18.04, .github/workflows/manually_centos_test_image.yml, .github/workflows/manually_repository_setup.yml
Update test images to occlum 0.21.0:centos8.2 and occlum 0.21.0:ubuntu 18.04. In addition, update the install method of docker to adapt new images.
=> CI/CD: adapte to occlum 0.21.0 with centos8.2 and ubuntu 18.04

.github/workflows/nightly-ubuntu-sgx1.yml
=> CI/CD: eliminate the warning of target translations are configured multiple times in kubernetes.list 

.github/workflows/nightly-ubuntu-sgx1.yml
unable to access 'https://github.com/alibaba/inclavare-containers/':
gnutls_handshake() failed: Error in the pull function. This error is
solved by configuring git proxy.
=> CI/CD: fix the error of unable to access inclavare-containers repository

.github/workflows/commit_crictl.yml, .github/workflows/commit_epm.yml, .github/workflows/commit_occlum.yml, .github/workflows/commit_skeleton.yml
Current CI/CD uses `sgxsdk 2.13` and `DCAP 1.10` which is corresponding to
version `1.41 DCAP driver`. In the [1.41 DCAP
driver](https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/DCAP_1.10/driver/linux/driver.c),
the `.nodename` of `struct miscdevice sgx_dev_enclave` and `struct miscdevice sgx_dev_provision`
are `sgx_enclave` and `sgx_provision` rather than `sgx/enclave` and `sgx/provision`.
=> CI/CD: update sgx DCAP driver to version 1.41

.github/workflows/nightly-centos-sgx1.yml, .github/workflows/nightly-ubuntu-sgx1.yml
There are two reasons to remove /var/run/epm:
- epm deb and rpm package will mkdir /var/run/epm automatically.
- the default centos 8.2 and ubuntu 18.04 don't have a /var/run/epm directory any more.
Fixes: #690
=> CI/CD: add rm -rf /var/run/epm in the nightly test

.github/workflows/nightly-ubuntu-sgx1.yml
nightly ubuntu: Specify the version of the sgx and dcap packages explicitly instead of 
installing the latest version from the repository
Fixes:#687
=> nightly ubuntu: Specify the version of the sgx and dcap packages

README.md, rune/README.md, rune/dist/deb/debian/control, rune/dist/rpm/rune.spec, sgx-tools/README.md, sgx-tools/dist/deb/debian/control, sgx-tools/dist/rpm/sgx-tools.spec
1. rune && sgx-tools: fix a spelling error in README.md.
2. rune/dist && sgx-tools/dist: remove the indirect libsgx-dcap-quote-verify dependency.
3. rune && sgx-tools: remove the indirect libsgx-dcap-quote-verify dependency in README.md.
=> rune && sgx-tools: update dependency in README.md, rpm spec, and deb control.

rune/libenclave/check.go
=> rune: fix unable to mount sgx device pointing to the relative path

enclave-tls/samples/enclave-tls-client/client.c, enclave-tls/samples/enclave-tls-server/server.c
The enclave-tls server in Occlum will transmit mrencalve and mrsigner
value of enclave to inclavared. The buff[0:31] is mrencalve value,
buff[32:63] is mrsigner value.
Fixes: #651
=> enclave-tls: implement enclave tls server application in Occlum

rune/libenclave/epm/procmaps.go
SGX device node has been changed from /dev/sgx/enclave to /dev/sgx_enclave.
This implementation matches with this change.
Fixes: #638
=> rune/libenclave/epm: add support for sgx kernel driver upstreamed

enclave-tls/README.md, enclave-tls/samples/enclave-tls-client/client.c, enclave-tls/samples/enclave-tls-server/server.c
=> enclave-tls/samples: allow to specify listening address and port and allow enclave-tls-server to be alive by default

rune/libenclave/epm/procmaps.go
=> rune/libenclave/epm: fix a typo about pathname of SGX device node

MAINTAINERS.md
=> MAINTAINERS.md: add two intel co-maintainers

enclave-tls/samples/enclave-tls-client/Makefile
The patch fixes the error "cc -pie -fPIE
-I/root/rpmbuild-rune/SOURCES/inclavare-containers-0.6.1/enclave-tls/src/include
client.c -o
/root/rpmbuild-rune/SOURCES/inclavare-containers-0.6.1/enclave-tls/build/bin/enclave-tls-client
-L/root/rpmbuild-rune/SOURCES/inclavare-containers-0.6.1/enclave-tls/build/lib
-lenclave_tls -Wl,--rpath=/opt/enclave-tls/lib,--enable-new-dtags
-lsgx_urts -lm
client.c: In function ‘enclave_tls_echo’:
client.c:102:3: error: ‘for’ loop initial declarations are only allowed
in C99 mode
for (int i = 0; i < 32; ++i)
^
client.c:102:3: note: use option -std=c99 or -std=gnu99 to compile your
code
client.c:106:12: error: redefinition of ‘i’
for (int i = 32; i < 64; ++i)
^
client.c:102:12: note: previous definition of ‘i’ was here
for (int i = 0; i < 32; ++i)
^ …
=> enclave-tls: add -std=c99 CFLAGS to fix gcc 4.8.5 compile error in alinux2

enclave-tls/src/enclave_quotes/sgx-la/collect_evidence.c, enclave-tls/src/enclave_quotes/sgx-la/ecalls.c, enclave-tls/src/enclave_quotes/sgx-la/sgx_la.edl, enclave-tls/src/enclave_quotes/sgx-la/verify_evidence.c, enclave-tls/src/tls_wrappers/wolfssl-sgx/wolfssl_sgx.edl
Getting App enclave's local report taking QE's target info as parameter,
verifier can verify the report from attester by sgx_qe_get_quote indirectly.
Fixes: #813
=> enclave-tls: change sgx local attestation's verification mode

.github/workflows/commit_enclave_tls.yml
Currently local attestation implementation is leveraging QE in DCAP to indirect verification
for ISV enclave local report. So local attastation has to run on SGX2 machine.
Fixes: #838 #827
=> .github/workflows: make local attestation run on SGX2 machine only

.github/workflows/docker/Dockerfile-compilation-testing-alinux2
Alibaba Cloud teesdk(https://help.aliyun.com/document_detail/208095.html) is owned by
Alibaba Cloud and supports the Alibaba Cloud Linux 2 OS image, so we change to use the
Alibaba Cloud teesdk and protobuf 2.5.0 in the Alibaba Cloud Linux 2 compilation test dockerfile.
=> workflows/docker: change to use the Alibaba Cloud teesdk and protobuf 2.5.0 in the alinux2 compilation test dockerfile

enclave-tls/README.md, enclave-tls/samples/enclave-tls-client/client.c, enclave-tls/samples/enclave-tls-server/server.c
=> enclave-tls: set the debug flag used in sgx_create_enclave() in smart  way

.github/workflows/docker/Dockerfile-compilation-testing-alinux2, .github/workflows/pr_basic_compilation_check.yml
- workflows/docker: fix the protobuf-c-devel version error
- The protobuf 2.5.0 corresponding protobuf-c-devel is 1.0.2
- CI/CD: add source /root/.bashrc in the compilation checks
=> CI/CD: Minor fixes

shelter/Makefile
SGX SDX can be installed in the standard patch(such as '/opt/intel/sgxsdk') and
can be also installed in the non-standard patch(such as
'/opt/alibaba/teesdk/intel/sgxsdk' in the Alibaba teesdk). So we use the
'?=' to replace the ':=' to support both the standard and non-standard
installed path.
=> shelter/Makefile: support SGX SDK installed in the non-standard path

rune/libenclave/internal/runtime/pal/skeleton/tls-server.c
The ENCLAVE_TLS_HELLO string in the skeleton/tls-server.c should be
equal to the ENCLAVE_TLS_HELLO string in enclave-tls client and server.
Fixes: #895
=> skeleton/tls-server.c: fix the invalid response retrieved from enclave-tls server error

shelter/README.md
In the go.mod file of shelter, shelter depends on golang 1.14 or above.
=> shelter/README.md: fix the dependent go version error

shelter/remoteattestation/securitychannel.go
The patch fixes the error "
CGO_ENABLED=1 go build "-mod=vendor" -buildmode=pie   -ldflags "" -o shelter .
ratlsclient.c: In function ‘ra_tls_echo’:
ratlsclient.c:67:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
for (int i = 0; i < 32; ++i)
^
ratlsclient.c:67:3: note: use option -std=c99 or -std=gnu99 to compile your code
ratlsclient.c:71:12: error: redefinition of ‘i’
for (int i = 32; i < 64; ++i)
^
ratlsclient.c:67:12: note: previous definition of ‘i’ was here
for (int i = 0; i < 32; ++i)
^
ratlsclient.c:71:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
for (int i = 32; i < 64; ++i)
^
make: *** [shelter] Error 2"
=> shelter/remoteattestation: add -std=gnu11 CGO FLAGS to fix gcc 4.8.5 compile error in alinux2

enclave-tls/src/tls_wrappers/wolfssl-sgx/ecalls.c
../tls_wrappers/wolfssl-sgx/ecalls.c: In function ‘recv’:
../tls_wrappers/wolfssl-sgx/ecalls.c:66:6: warning: unused variable ‘sgxStatus’ [-Wunused-variable]
int sgxStatus = ocall_recv(&ret, sockfd, buf, len, flags);
^~~~~~~~~
../tls_wrappers/wolfssl-sgx/ecalls.c: In function ‘send’:
../tls_wrappers/wolfssl-sgx/ecalls.c:75:6: warning: unused variable ‘sgxStatus’ [-Wunused-variable]
int sgxStatus = ocall_send(&ret, sockfd, buf, len, flags);
^~~~~~~~~
CC   <=  ../tls_wrappers/wolfssl-sgx/ecalls.c
Fixes: #790
=> enclave-tls: fix build warnings about wolfssl-sgx

enclave-tls/dist/rpm/enclave_tls.spec, epm/dist/rpm/epm.spec, inclavared/dist/rpm/inclavared.spec, rune/dist/rpm/rune.spec, sgx-tools/dist/rpm/sgx-tools.spec, shelter/dist/rpm/shelter.spec, shim/dist/rpm/shim-rune.spec
1. {rune,epm,shim,sgx-tools,shelter}/dist: fix typos in rpm specs
2. enclave-tls/dist: support the debuginfo rpm package
3. {shelter,inclavared}/dist: drop the AutoReq section and add the enclave-tls build requires
4.  inclavared/dist: add the rustc anc cargo check in the %build section rather than in the BuildRequires section
=> {rune,epm,shim,sgx-tools,shelter}/dist: minor fixes in the rpm specs and support the enclave-tls debuginfo rpm package

.github/workflows/nightly-centos-sgx1.yml
=> CI/CD: avoid building the shelter rpm package in the nightly centos SGX1 test

inclavared/app/src/main.rs
Because the enclave associated with the tls handle is freed before
the tls handle, the ecall in cleanup() fails. so the tls handle is
freed in advance, instead of being freed automatically by the
compiler after leaving the scope.
Fixes: #969
=> inclavared: Fix the failure of calling enclcave_tls_cleanup()

.github/workflows/nightly-centos-sgx1.yml, .github/workflows/pr_epm.yml, .github/workflows/pr_skeleton.yml
=>  CI/CD: avoid building the inclavared rpm package in the pr tests and nightly tests

enclave-tls/dist/rpm/enclave_tls.spec
Signed-off-by: Chunmei Xu <xuchunmei@linux.alibaba.com>
=> enclave-tls/dist: fix build the debuginfo rpm package failed in the centos 8.x

shelter/dist/deb/build.sh, shelter/dist/deb/debian/control, shelter/dist/deb/debian/rules
1. shelter/dist: add the build depends of the deb packages.
2. shelter/dist: fix unrecognized option '-Wl,-Bsymbolic-functions' error
3. shelter/dist: add override_dh_auto_clean in the deb package rules
Fixes: #976
=> shelter/dist: minor fixes in the deb package control and rules

inclavared/dist/deb/build.sh, inclavared/dist/deb/debian/control
1. inclavared/dist: add enclave-tls build-depends in the deb package
2. inclavared/dist: add the rustc anc cargo check in the build.sh rather than in the build-depends section for the deb package
Fixes: #977
Fixes: #978
=> inclavared/dist: minor fixes in the inclavared deb packages

.github/workflows/nightly-ubuntu-sgx1.yml, epm/dist/deb/debian/rules, sgx-tools/dist/deb/debian/rules, shim/dist/deb/debian/rules
1. CI/CD: avoid building shelter and inclavared packages in the nightly ubuntu SGX1 test
2. {epm, shim, sgx-tools}: add override_dh_auto_clean in the deb package rules
=> CI/CD: minor fixes about building deb packages error in the nightly SGX1 ubuntu test

enclave-tls/dist/deb/debian/rules, enclave-tls/dist/rpm/enclave_tls.spec
enclave-tls debuginfo rpm and dbgsym deb package will rebuild sgx_stub_enclave.signed.so in the
incorrect pattern, it will casue enclave-tls-sever load enclave failed. So we
avoid building the enclave-tls debuginfo rpm and dbgsym deb package to workaround this problem.
=> enclave-tls/dist: both avoid building the enclave-tls debuginfo rpm and dbgsym deb package

enclave-tls/samples/enclave-tls-server/server.c
=> enclave-tls: fix the \n\u0000 in the shelter output information

enclave-tls/dist/deb/debian/rules
According to https://man7.org/linux/man-pages/man1/dh_strip.1.html, we can use
dh_strip --exclude to exclude the files from being stripped. If the sgx_stub_enclave.signed.so
file is stripped, it will be an error, so we should use dh_strip --exclude rules to avoid
stripping them.
Fixes: #1006
=> enclave-tls/dist: add dh_strip --exclude rules in the deb and dbgsym packages

enclave-tls/dist/rpm/enclave_tls.spec
Because in centos 8.x, rpmbuild has a higher 4.14 version,
and introduces the debugsource sub-packages. So it is not
easy to disable the strip operation, so we customized the
__enclave_tls_install_post and __spec_install_post macros.
The __enclave_tls_install_post macro is executed after
the stripping and we use the sgx_stub_enclave.signed.so which
generated during compilation to replaces the corresponding stripped
one which generated during the install phase.
As a result, we ensure the correct operation of enclave-tls-server/client,
and successfully generate the debuginfo and debugsource subpackages
of enclave-tls.
Fixes: #1029
=> enclave-tls/dist: support debuginfo packages that can run enclave-tls-server/client successfully in centos 8.2

enclave-tls/src/enclave_quotes/sgx-ecdsa/ecalls.c
=> enclave-tls: fix build warning when make SGX=1

enclave-tls/src/Makefile, enclave-tls/src/crypto_wrappers/api/crypto_wrapper_register.c, enclave-tls/src/crypto_wrappers/wolfcrypt-sgx/main.c, enclave-tls/src/enclave_quotes/api/enclave_quote_register.c, enclave-tls/src/enclave_quotes/internal/etls_enclave_quote_select.c, enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/main.c, enclave-tls/src/enclave_quotes/sgx-la/main.c, enclave-tls/src/include/internal/sgxutils.h, enclave-tls/src/tls_wrappers/api/tls_wrapper_register.c, enclave-tls/src/tls_wrappers/wolfssl-sgx/main.c, enclave-tls/src/util/sgxutils.c
Fixes: #844
* Set flags for wolfssl_sgx, wolfcrypto_sgx, sgx_la, sgx_ecdsa_qve to 1 as
platform requirement
* Detect platform capabilities while selecting instances
Signed-off-by: Ruoyu.Ying <ruoyu.ying@intel.com>
=> enclave-tls: enable capability flags in the register of enclave quote instance

enclave-tls/src/crypto_wrappers/api/crypto_wrapper_register.c, enclave-tls/src/crypto_wrappers/internal/etls_crypto_wrapper_load_single.c, enclave-tls/src/crypto_wrappers/internal/etls_crypto_wrapper_select.c, enclave-tls/src/crypto_wrappers/nullcrypto/main.c, enclave-tls/src/crypto_wrappers/wolfcrypt-sgx/main.c, enclave-tls/src/crypto_wrappers/wolfcrypt/gen_cert.c, enclave-tls/src/crypto_wrappers/wolfcrypt/main.c, enclave-tls/src/enclave_quotes/api/enclave_quote_register.c, enclave-tls/src/enclave_quotes/internal/etls_enclave_quote_load_single.c, enclave-tls/src/enclave_quotes/internal/etls_enclave_quote_select.c, enclave-tls/src/enclave_quotes/nullquote/main.c, enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/main.c, enclave-tls/src/enclave_quotes/sgx-ecdsa/collect_evidence.c, enclave-tls/src/enclave_quotes/sgx-ecdsa/main.c, enclave-tls/src/enclave_quotes/sgx-ecdsa/verify_evidence.c, enclave-tls/src/enclave_quotes/sgx-la/main.c, enclave-tls/src/external/wolfssl/patch/wolfssl.patch, enclave-tls/src/include/enclave-tls/crypto_wrapper.h, enclave-tls/src/include/enclave-tls/enclave_quote.h, enclave-tls/src/include/enclave-tls/tls_wrapper.h, enclave-tls/src/tls_wrappers/api/tls_wrapper_register.c, enclave-tls/src/tls_wrappers/api/tls_wrapper_verify_certificate_extension.c, enclave-tls/src/tls_wrappers/internal/etls_tls_wrapper_load_single.c, enclave-tls/src/tls_wrappers/internal/etls_tls_wrapper_select.c, enclave-tls/src/tls_wrappers/nulltls/main.c, enclave-tls/src/tls_wrappers/wolfssl-sgx/main.c, enclave-tls/src/tls_wrappers/wolfssl/main.c, enclave-tls/src/tls_wrappers/wolfssl/oid.c, enclave-tls/src/tls_wrappers/wolfssl/un_negotiate.c, enclave-tls/src/tls_wrappers/wolfssl/wolfssl.h
Tested by enclave-tls-server -m -a sgx_ecdsa|sgx_ecdsa_qve -v sgx_ecdsa|sgx_ecdsa_qve and enclave-tls-client -m -a sgx_ecdsa|sgx_ecdsa_qve -v sgx_ecdsa|sgx_ecdsa_qve
=> enclave-tls: allow sgx_ecdsa instance to support the evidence generatd by sgx_ecdsa_qve

shelter/dist/deb/debian/changelog, shelter/dist/rpm/shelter.spec
The shelter centos 8.2 rpm and ubuntu 18.04 deb package is needed by ACK-TEE,
So we need to update the shelter rpm and deb version to 0.6.1
=> shelter/dist: update rpm and deb version to 0.6.1

.github/workflows/pr_enclave_tls.yml, .github/workflows/pr_shelter.yml
Since the attester and verifier are logically splitted, the workflow
should explicitly specify -v nullquote. Otherwise, the best choice,
e.g, sgx_ecdsa_qve, will be selected and thus failed to verify the
evidence for sure.
=> workflow: fix CI/CD failure due to the lack of -v nullquote

shelter/dist/deb/debian/changelog
This patch fixes the dpkg-buildpackage warning:
dpkg-gencontrol: warning:     debian/changelog(l5): badly formatted trailer line
LINE:  -- Yilin Li <YiLin.Li@linux.alibaba.com>  Sat, May 22 2021 15:40:00 +0000
dpkg-gencontrol: warning:     debian/changelog(l7): found start of entry where expected more change data or trailer
LINE: shelter (0.6.0-1) unstable; urgency=low
dpkg-gencontrol: warning:     debian/changelog(l7): found end of file where expected more change data or trailer
dpkg-gencontrol: warning:     debian/changelog(l5): badly formatted trailer line
LINE:  -- Yilin Li <YiLin.Li@linux.alibaba.com>  Sat, May 22 2021 15:40:00 +0000
dpkg-gencontrol: warning:     debian/changelog(l7): found start of entry where expected more change data or trailer
LINE: shelter (0.6.0-1) unstable; …
=> shelter/dist: fix the badly formatted trailer line warning

.github/workflows/pr_epm.yml
This patch fix the error:
[Errno 2] No such file or directory: '/var/cache/dnf/metadata_lock.pid'
=> workflows/pr_epm: fix CI/CD failure due to metadata_lock.pid does not exist

rune/dist/deb/debian/changelog, rune/dist/rpm/rune.spec, sgx-tools/dist/deb/debian/changelog, sgx-tools/dist/rpm/sgx-tools.spec
=> rune & sgx-tools: bump the versions of deb and rpm to 0.6.1

.github/workflows/pr_crictl.yml, .github/workflows/pr_enclave_tls.yml, .github/workflows/pr_epm.yml, .github/workflows/pr_occlum.yml, .github/workflows/pr_shelter.yml, .github/workflows/pr_skeleton.yml
Unsupported sock5 proxy in apt-get. Therefore, we use http proxy instead.
Fixes: #1064
=> CI/CD: configure proxy for normal network traffic

.github/workflows/pr_epm.yml
This patch fix the error:
[Errno 2] No such file or directory: '/var/cache/dnf/metadata_lock.pid'
We have systemd dnf-makecache.timer running (its set up by default) which periodically
runs `dnf makecache --timer`, and if we do our command `yum install -y wget` at the same
time while the makecache is running with deleting the lock file in /var/cache/dnf/,
both transactions run at the same time and everything breaks. This is the reason why
the very irregular occurrence since we have to hit the exact time the timer starts makecache.
Please see https://bugzilla.redhat.com/show_bug.cgi?id=1814337 for more information.
=> CI/CD: stop dnf-makecache.timer service when install centos dependency

rune/libenclave/init_linux.go
=> rune: fix the process name encoding error

.github/workflows/pr_epm.yml
Install enclave-tls package will introduce new runtime dependencies
which is not required by epm test.
Fixes: #1164
=> pr_epm: do not install enclave-tls deb

rune/libenclave/internal/runtime/pal/skeleton/Makefile
aesm.c requires aesm.pb-c.[ch] but they are not explicitly listed in the
dependency.
Fixes: #1132
=> rune/skeleton: fix build failure due to wrong dependency to aesm.pb-c.c

enclave-tls/src/Makefile
This patch solves the error when setting DEBUG=1: hidden symbol `stat' in
/usr/lib/x86_64-linux-gnu/libc_nonshared.a(stat.oS) is referenced by DSO.
Fixes: #1172
=> enclave-tls: add debug mode

enclave-tls/src/crypto_wrappers/openssl/gen_cert.c, enclave-tls/src/include/enclave-tls/oid.h, enclave-tls/src/tls_wrappers/openssl/openssl.h, enclave-tls/src/tls_wrappers/openssl/un_negotiate.c
=> enclave-tls: extract oid definition into a global header file

shelter/dist/deb/debian/rules
This patch is to fix the dpkg-shlibdep error: no dependency
information found for /opt/enclave-tls/lib/libenclave_tls.so.0
(used by debian/shelter/usr/local/bin/shelter).
=> shelter/dist: fix make package error in ubuntu

enclave-tls/src/crypto_wrappers/openssl/gen_cert.c
The reason for the failure of OBJ_create() is due to repeated creation,
so first look up the Object ID, and then create it if it fails.
Fixes: #1195
Fixes: #1196
=> enclave-tls: Fix the issue of OBJ creation failure

rune/dist/deb/debian/changelog, rune/dist/rpm/rune.spec, sgx-tools/dist/deb/debian/changelog, sgx-tools/dist/rpm/sgx-tools.spec
=> rune & sgx-tools: bump the versions of deb and rpm to 0.6.2

.github/actions/clean-nightly-env/aliyunlinux/action.yaml, .github/actions/clean-nightly-env/centos/action.yaml, .github/actions/clean-nightly-env/ubuntu/action.yaml, .github/workflows/nightly-aliyunlinux-sgx2.yml, .github/workflows/nightly-centos-sgx1.yml, .github/workflows/nightly-ubuntu-sgx1.yml
1. Specify cri-socket explicitly when initializing k8s cluster.
2. Install the sgx stack in centos nightly cicd.
=> cicd: Fix the centos nightly task

enclave-tls/dist/deb/debian/changelog, enclave-tls/dist/rpm/enclave_tls.spec, epm/dist/deb/debian/changelog, epm/dist/rpm/epm.spec
=> enclave-tls & epm: bump the version of deb and rpm to 0.6.2

enclave-tls/src/verifiers/internal/etls_enclave_verifier_load_single.c
=> enclave-tls: mute the unnnecessary errors due to the lack of sgx capability

verdictd/app/Cargo.toml, verdictd/app/build.rs, verdictd/app/src/enclave_tls/ffi.rs, verdictd/app/src/enclave_tls/mod.rs, verdictd/app/src/main.rs
Verdictd will use Enclave-tls to receive requests from Attestation Agent. 
Currently it can receive request from enclave-tls-client with following command:
./enclave-tls-client --attester sgx_ecdsa --verifier nullverifier --tls openssl --crypto openssl --mutual --ip 127.0.0.1 --port 1122
=> verdictd: Integrated Enclave-tls into verdictd

verdictd/app/src/key_manager/directory_key_manager.rs, verdictd/app/src/key_manager/mod.rs, verdictd/app/src/main.rs
This simple key manager module will get key from /opt/verdictd/keys/ path according to input kid.
=> verdictd: add key manager module

rats-tls/src/crypto_wrappers/openssl/openssl.h
under openssl1.0.x, there is no store.h, so it will generate
compilation error as below:
fatal error: openssl/store.h: No such file or directory
Fixes: #1290
=> rats-tls: sovle compilation error under openssl1.0.x env

rats-tls/cmake/CMakeUninstall.cmake.in, rats-tls/cmake/CustomInstallDirs.cmake, rats-tls/src/include/internal/attester.h, rats-tls/src/include/internal/crypto_wrapper.h, rats-tls/src/include/internal/tls_wrapper.h, rats-tls/src/include/internal/verifier.h
=> rats-tls: only install enclave-tls sdk files to /opt/enclave-tls

enclave-tls/dist/deb/debian/changelog, enclave-tls/dist/rpm/enclave_tls.spec, epm/dist/deb/debian/changelog, epm/dist/rpm/epm.spec
=> epm & enclave-tls: bump the versions of deb and rpm to 0.6.3

rats-tls/src/attesters/internal/etls_enclave_attester_load_all.c, rats-tls/src/crypto_wrappers/internal/etls_crypto_wrapper_load_all.c, rats-tls/src/tls_wrappers/internal/etls_tls_wrapper_load_all.c, rats-tls/src/verifiers/internal/etls_enclave_verifier_load_all.c
=> rats-tls: set DT_LNK value to avoid compiling error under SGX mode

rats-tls/src/verifiers/sgx-ecdsa/CMakeLists.txt
In sgx 2.14, libsgx_dcap_quoteverify.so lacks of pthread_create_ocall,
pthread_wakeup_ocall, and pthread_wait_timeout_ocall symbols which are
defined in sgx_urts library.
=> rats-tls: add sgx_urts in link library

rune/docs/pal_programming_guide.md
There is a small typo in rune/docs/pal_programming_guide.md.
Should read `runtime` rather than `rumtime`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, rumtime -> runtime

CONTRIBUTING.md
=> CONTRIBUTING.md: add the step to install clang-format for CentOS8

.github/workflows/manually_repository_setup.yml, .github/workflows/nightly-aliyunlinux-sgx2.yml, docs/create_a_confidential_computing_kubernetes_cluster_with_inclavare_containers.md, inclavare-containers.io/content/en/guides/create-k8s-inclavare-containers/index.md, inclavare-containers.io/content/en/guides/qucik-start/index.md
The url of https://mirrors.openanolis.org is replaced by https://mirrors.openanolis.cn.
Fixes: #1461
=> docs: update repo url to https://mirrors.openanolis.cn

enclave-tls/dist/Makefile
This patch resolves the following error:
make deb
make[2]: Entering directory '/root/yijuan/ic_test/inclavare-containers-0.6.4/enclave-tls/dist'
dpkg-buildpackage: warning:     debian/changelog(l1): badly formatted heading line
LINE: enclave_tls (0.6.4-1) unstable; urgency=low
dpkg-buildpackage: warning:     debian/changelog(l2): found blank line where expected first heading
dpkg-buildpackage: warning:     debian/changelog(l3): found change data where expected first heading
LINE:   * Update to version 0.6.4.
dpkg-buildpackage: warning: unknown information field '' in input data in parsed version of changelog
dpkg-buildpackage: info: source package unknown
dpkg-buildpackage: info: source version unknown
dpkg-buildpackage: error: version number does not start with digit
Fixes: #1515 …
=> enclave-tls: fix version number does not start with digit error

shim/go.mod, shim/go.sum
Upgrade distribution package to 2.8.0 to fix OCI
Manifest Type Confusion Issue.
=> shim: upgrade distribution package to 2.8.0

rune/libenclave/runelet.go
The first parameter of func KillPayload(pid int, sig int)
is pid rather than sig.
=> rune: fix the wrong input parameter in KillPayload
