inclavare-containers/inclavare-containers

rune/libenclave/internal/runtime/pal/pal_linux.go
=> Open logs of the Enclave Runtime

rune/libcontainer/specconv/spec_linux.go
Instead creating devices in Enclave Containers without examining.
=> rune: Only create default character devices in Enclave Containers

README.md
=> README: Add the info about new component runectl

rune/libenclave/runelet.go
If the program launched by rune exec is terminated, runelet process
is unstoppable. Just kick off it through the channel notifyExit.
Signed-off-by: Xiaozhe Wang <wangxiaozhe@linux.alibaba.com>
=> rune/libenclave: Fix runelet process to exit

rune/libenclave/agent.go, rune/libenclave/utils.go
Signed-off-by: jack.wxz <wangxiaozhe@linux.alibaba.com>
=> Use pipe instead of net.FileConn to read protobuf.

rune/libenclave/runelet.go
It should be not so complex to cast client agent pipe in so many forms.
=> rune/libenclave: Simplify access to client agent pipe used by remote exec

rune/Makefile, rune/libenclave/internal/runtime/pal/skeleton/Makefile, rune/libenclave/internal/runtime/pal/skeleton/README.md, rune/libenclave/internal/runtime/pal/skeleton/arch.h, rune/libenclave/internal/runtime/pal/skeleton/defines.h, rune/libenclave/internal/runtime/pal/skeleton/encl.c, rune/libenclave/internal/runtime/pal/skeleton/encl.lds, rune/libenclave/internal/runtime/pal/skeleton/encl_bootstrap.S, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/pal.h, rune/libenclave/internal/runtime/pal/skeleton/sgx.h, rune/libenclave/internal/runtime/pal/skeleton/sgx_call.S, rune/libenclave/internal/runtime/pal/skeleton/sgx_call.h, rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
Signed-off-by: jack.wxz <wangxiaozhe@linux.alibaba.com>
=> run skeleton in enclave.

README.md
=> README: Update to reflect the status of shim-rune

rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
=> rune/libenclave: Code clean up for skeleton

rune/libenclave/internal/runtime/pal/skeleton/README.md
=> rune/libenlave/skeleton: Update README for usage

rune/libcontainer/nsenter/loader.c, rune/libcontainer/nsenter/loader.go, rune/libenclave/internal/runtime/pal/api_linux_v1.go, rune/libenclave/internal/runtime/pal/api_linux_v2.go, rune/libenclave/internal/runtime/pal/pal_linux.go
Signed-off-by: jack.wxz <wangxiaozhe@linux.alibaba.com>
=> rune/libenclave: support pal api to v2

rune/libenclave/agent.go, rune/libenclave/internal/runtime/enclave_runtime.go, rune/libenclave/internal/runtime/pal/api_linux_v1.go, rune/libenclave/internal/runtime/pal/api_linux_v2.go, rune/libenclave/internal/runtime/pal/pal_linux.go
=> rune/libenclave: Move pal_kill implementation to v2 API

rune/libcontainer/configs/validate/validator.go, rune/libcontainer/container_linux.go
=> rune: Minor code cleanup

rune/libcontainer/specconv/example.go, rune/libenclave/init.go
=> rune/libenclave: Implement new ecall get_report()

rune/libenclave/internal/runtime/pal/skeleton/README.md
1. Add way to build and install rune.
2. Add way to configure rune to Docker runtimes.
=> rune/libenclave: Update skeleton README.md

README.md
=> rune: Update README for runectl

README.md, docs/running_rune_with_occlum.md, docs/running_rune_with_occlum_bundle.md, rune/libenclave/internal/runtime/pal/skeleton/README.md, rune/libenclave/internal/runtime/pal/spec_v1.md, rune/libenclave/internal/runtime/pal/spec_v2.md
=> docs: Refresh docs for 0.2.0 release

rune/libenclave/attestation/sgx/ias/api.go, rune/libenclave/attestation/sgx/ias/ias.go
Both support IAS API V3 and V4.
=> rune/libenclave: support IAS V4 API

shim/Makefile
=> add rpm target in Makefile

rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
=> rune/libenclave: Some fix for liberpal-skleton

.gitignore, docs/running_rune_with_occlum.md, rune/dist/Makefile, shim/dist/Makefile
- Add command to launch a CentOS 7.5 container
- Update Occlum SDK container image to 0.14.0
=> docs: Update running_rune_with_occlum.md

rune/libenclave/attestation/check.go, rune/libenclave/attestation/nonce.go, rune/libenclave/attestation/registry.go, rune/libenclave/attestation/service.go, rune/libenclave/attestation/sgx/ias/api.go, rune/libenclave/attestation/sgx/ias/ias.go, rune/libenclave/attestation/utils.go, rune/libenclave/attestation/verify.go
=> rune/libenclave: format the attestation package style to sync up to rune.

rune/libcontainer/configs/validate/validator.go, rune/libcontainer/specconv/spec_linux.go, rune/libenclave/attestation/sgx/attest.go
=> rune: set enclave attestation remote attestation related parameters optional.

rune/libenclave/internal/runtime/pal/api_linux_v2.go
=> rune: Workround the argv problem between rune and occlum

README.md, docs/terminology.md
=> Add terminology doc

rune/libenclave/internal/runtime/pal/api_linux_v2.go
=> rune: Fix #93 (Workround the argv problem between rune and occlum)

rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/sgx.h
=> rune/libenclave/skeleton: Support SGX in-tree driver

docs/running_rune_with_occlum.md, docs/running_rune_with_occlum_bundle.md
- Add running rune on ubuntu 18.04-server in running_rune_with_occlum.md
- Add installing rune and occlum-pal with package in running_rune_with_occlum.md
- Update Dockerfile in running_rune_with_occlum.md
- Update the the path of enclave.runtime and rune in running_rune_with_occlum.md
- Update the "enclave.runtime.path" in running_rune_with_occlum_bundle.md
=> docs: Update 0.3.0 release docs for rune

rune/dist/deb/debian/changelog, rune/dist/deb/debian/control, rune/dist/rpm/rune.spec, shim/dist/deb/debian/changelog, shim/dist/deb/debian/control, shim/dist/deb/debian/postinst, shim/dist/rpm/shim-rune.spec
- Update rune.spec and shim-rune.spec to version 0.3.0
- Update rune and shim deb to version 0.3.0
=> rune && shim: Update rpm and deb to version 0.3.0

docs/running_rune_with_occlum.md
=> docs: Refresh docs for 0.3.0 release

rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
=> rune/libenclave/skeleton: Fix pal_exec() prototype according to v1

rune/libenclave/internal/runtime/pal/skeleton/Makefile, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v1.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.h
=> rune/libenclave/skeleton: Support api version 2

rune/libenclave/internal/runtime/pal/spec_v1.md, rune/libenclave/internal/runtime/pal/spec_v2.md
- Reformat spec_v1.md and spec_v2.md
=> rune/libenclave/pal: Reformat the pal spec

rune/libenclave/internal/runtime/pal/skeleton/Makefile, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c
=> rune/skeleton/sgxsign: Add --product option of sgxsign

rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
Since the pal_create_process interface of PAI API v2 has achieved a similar function, fork-test argument is useless.
=> rune/libenclave/skeleton: Remove fork-test argument

rune/libenclave/internal/runtime/pal/skeleton/Makefile, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v2.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v3.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.h, rune/libenclave/internal/runtime/pal/skeleton/skeleton_remote_attestation_with_rune.md
1. Support OOT driver in PAL API V2.
2. Support PAL API V3.
3. Support `rune attest` command.
4. Add skeleton_remote_attestation_with_rune.md.
=> Support OOT driver in PAL API V2 and Support PAL API v3

shim/runtime/v2/rune/types.go, shim/runtime/v2/rune/v2/rune.go, shim/runtime/v2/rune/v2/service.go
=> shim: add the skeleton Enclave Runtime carrier.

rune/libenclave/internal/runtime/pal/api_linux_v2.go
=> rune: Revert the argv problem between rune and occlum

rune/libenclave/internal/runtime/pal/skeleton/README.md
=> docs: Add skeleton supported PAL PAI version notes in README.md

shim/dist/deb/debian/changelog, shim/dist/deb/debian/postinst, shim/dist/rpm/shim-rune.spec
- Update deb to version 0.4.0
- Update rpm to version 0.4.0
=> shim: Update deb and rpm package to version 0.4.0

rune/dist/deb/debian/changelog, rune/dist/rpm/rune.spec
- Update deb to version 0.4.0
- Update rpm to version 0.4.0
=> rune: Update deb and rpm package to version 0.4.0

docs/running_rune_with_occlum.md, docs/running_rune_with_occlum_bundle.md, rune/libenclave/internal/runtime/pal/skeleton/README.md
- Update centos version from 7.5 to 8.1
- Update occlum version from 0.14.0 to 0.15.1
- Update the way to Install SGX SDK and SGX PSW
- Update ENCLAVE_RUNTIME_ARGS 
=> docs: Update 0.4.0 release docs for rune

shim/runtime/carrier/constants/constants.go, shim/runtime/carrier/occlum/occlum.go, shim/runtime/v2/rune/v2/service.go
shim-rune adapts to occlum 0.15.1
=> shim-rune adapts to occlum 0.15.1

docs/create_a_confidential_computing_kubernetes_cluster_with_inclavare_containers.md, docs/develop_and_deploy_hello_world_application_in_kubernetes_cluster.md
update the dosc for creating rune containers in Kubernetes cluster
=> update the dosc for creating rune containers in Kubernetes cluster

docs/create_a_confidential_computing_kubernetes_cluster_with_inclavare_containers.md, docs/develop_and_deploy_hello_world_application_in_kubernetes_cluster.md, shim/README-zh_CN.md, shim/README.md, shim/conf/config.toml
update the version number in doc files
=> update the version number in doc files

README.md, docs/running_rune_with_occlum.md, rune/libenclave/internal/runtime/pal/skeleton/README.md, sgx-tools/README.md
- Add Dragonwell and Skeleton images in reference container image
- Update Version number
=> docs: update docs for 0.4.0 release

shim/runtime/config/config.go
=> shim/runtime/config: Fix return value error in the GetEnv function

rune/libenclave/internal/runtime/pal/skeleton/sgx.h, rune/libenclave/internal/runtime/pal/skeleton/sgxutils.c
=> rune/libenclave/skeleton: Fix some code format problems.

ra-tls/README.md
=> ra-tls: Update README.md to keep consistent with 0.4.0

ra-tls/README.md
=> Revert "ra-tls: Update README.md to keep consistent with 0.4.0"

ra-tls/README.md
=> ra-tls: Update README to reflect current implementation

rune/libenclave/internal/runtime/pal/pal_linux.go
=> rune/libenclave: Support PAL API Version 3

rune/libenclave/internal/runtime/pal/skeleton/sgxutils.c
Signed-off-by: Shirong Hao shirong@linux.alibaba.com
=> rune/libenclave/skeleton: Reimplement the code of get_sgx_xfrm_by_cpuid

README.md
`sgx-tools` add a command to get remote attestation report from IAS.
=> README.md: Enhance the usage description of sgx-tools

rune/dist/deb/build.sh, rune/dist/deb/debian/changelog, rune/dist/rpm/rune.spec
- Add debug package in version 0.4.1
=> rune: Update deb and rpm package to version 0.4.1

ra-tls/README.md
Yilin Li <YiLin.Li@linux.alibaba.com>
=> ra-tls/README.md: add the `glibc-static` compilation dependency

rune/libenclave/internal/runtime/pal/spec.md
=> rune/libenclave/pal/spec.md: add the relationship between `exec` subcommand and PAL APIs

rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/sgx.h, rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c, rune/libenclave/internal/runtime/pal/skeleton/sgxutils.c
=> rune/skeleton: dynamically get the ssa_frame_size and mmap ssa_frame area

shim/Makefile, shim/dist/deb/build.sh, shim/dist/deb/debian/changelog, shim/dist/rpm/shim-rune.spec
update the version of makefile, rpm spec and deb scricpt file
=> shim-rune: update the version of makefile, rpm spec and deb scricpt file

docs/running_rune_with_occlum.md, docs/running_rune_with_occlum_bundle.md
=> docks: update to version 0.4.1

docs/create_a_confidential_computing_kubernetes_cluster_with_inclavare_containers.md, docs/develop_and_deploy_hello_world_application_in_kubernetes_cluster.md, shim/README-zh_CN.md, shim/README.md, shim/conf/config.toml, shim/config/config_test.go, shim/dist/deb/build.sh, shim/dist/deb/debian/postinst, shim/runtime/carrier/occlum/occlum.go, shim/runtime/utils/utils.go, shim/runtime/utils/utils_test.go, shim/runtime/v2/rune/v2/service.go
update docs and default configuration files for shim-rune
=> shim-rune: update docs and default configuration files for shim-rune

docs/running_rune_with_occlum.md
=> docs: fix the path of ENCLAVE_RUNTIME_PATH

CONTRIBUTING.md
=> CONTRIBUTING: add primary ways to contribute to project as an external contributor

rune/libenclave/container.go, rune/libenclave/container_linux.go, rune/libenclave/factory_linux.go
=> rune : save enclaveConfig in container state to fix the rune exec and rune attest error problem

rune/docs/pal_programming_guide.md, rune/libenclave/internal/runtime/pal/spec.md
=> rune/libenclave/pal: link pal_programming_guide.md in spec.md

CONTRIBUTING.md
=> CONTRIBUTING: add commit message format about fixing github issues

rune/libenclave/internal/runtime/pal/skeleton/arch.h, rune/libenclave/internal/runtime/pal/skeleton/defines.h, rune/libenclave/internal/runtime/pal/skeleton/encl.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v1.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v2.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v3.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.h, rune/libenclave/internal/runtime/pal/skeleton/sgx.h, rune/libenclave/internal/runtime/pal/skeleton/sgx_call.h, rune/libenclave/internal/runtime/pal/skeleton/sgxsign.c, rune/libenclave/internal/runtime/pal/skeleton/sgxutils.c
=> rune/skeleton: format code style using indent tool

rune/libenclave/internal/runtime/pal/skeleton/.gitignore, rune/libenclave/internal/runtime/pal/skeleton/Makefile, rune/libenclave/internal/runtime/pal/skeleton/README.md, rune/libenclave/internal/runtime/pal/skeleton/aesm.c, rune/libenclave/internal/runtime/pal/skeleton/aesm.h, rune/libenclave/internal/runtime/pal/skeleton/aesm.proto, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
=> rune/skeleton: support to dynamically generate launch token in skeleton

rune/README.md
=> rune/README: add credit info

rune/dist/deb/debian/changelog, rune/dist/rpm/rune.spec, sgx-tools/dist/deb/debian/changelog, sgx-tools/dist/rpm/sgx-tools.spec
=> rune && sgx-tools: update deb and rpm package to version 0.5.0

rune/libenclave/internal/runtime/pal/api_linux_v1.go, rune/libenclave/internal/runtime/pal/api_linux_v3.go, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v1.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v2.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v3.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.h
=> skeleton: reconstruct pal init api v1 and v3

docs/Running_Occlum_with_Docker_and_OCI_Runtime_rune.md
=> docs: reflect the release version 0.5.0

CONTRIBUTING.md
=> CONTRIBUTING: add the description of C code style

patch/no-sgx-flc/README.md
Support the SGX SDK [SampleEnclave](https://github.com/intel/linux-sgx/tree/master/SampleCode/SampleEnclave) code validation.
=> patch/no-sgx-flc/README.md: support SGX SDK sample codes validation

README.md
=> README: document a Deployment section instead of Running

patch/no-sgx-flc/README.md
=> patch/no-sgx-flc/README.md: set in-tree driver patch depreciated

rune/libenclave/internal/runtime/pal/skeleton/encl.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/sgx_call.h
=> rune/skeleton: print out Hello Inclavare when initialization

docs/design/terminology.md, rune/libenclave/internal/runtime/pal/skeleton/README.md
=> docs: update various docs

README.md, rune/dist/deb/debian/rules, rune/dist/rpm/rune.spec
=> rune: make package install path to /usr/local/bin/rune

shim/runtime/v2/rune/v2/rune.go, shim/runtime/v2/rune/v2/service.go
fix a bug that failed to create runc containers in client mode
=> shim-rune: fix a bug that failed to create runc containers in client mode

rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v3.c
=> rune/libenclave/skeleton: run an enclave ecall exapmle in pal v3

rune/libenclave/internal/runtime/pal/skeleton/running_skeleton_with_rune_attest_command.md
=> rune/libenclave/skeleton/readme.md: set the host network mode when get IAS report

rune/libenclave/internal/runtime/pal/skeleton/README.md
=> rune/libenclave/skeleton: link running_skeleton_with_rune_attest_command.md in README.md

README.md, epm/README.md
=> README: add epm description and fix epm install path

rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
=> rune/libenclave/skeleton: check whether memory is successfully allocated

docs/create_a_confidential_computing_kubernetes_cluster_with_inclavare_containers.md, epm/README-zh_CN.md, epm/dist/deb/debian/control, epm/dist/deb/debian/postinst, epm/dist/deb/debian/rules, epm/dist/rpm/epm.spec, rune/libenclave/internal/runtime/pal/skeleton/Makefile
=> docs && epm: fix a typo  and make epm install path to /usr/loca/bin/epm

patch/no-sgx-flc/0001-SGX-DCAP-Linux-Driver-Support-SGX1-machine-even-without-FLC-s.patch
=> patch/no-sgx-flc: support DCAP v1.36.2 Linux driver

CONTRIBUTING.md
=> CONTRIBUTING.md: fix a typo

.github/workflows/rune_with_docker_and_crictl.yml
=> workflow: add rune with docker and crictl integration testing

rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
=> rune/libenclave/skeleton: fix return value error

ra-tls/pal/App.c, ra-tls/ra-tls-server/lib/ra-tls-server.c
The untrusted side checks the return value of wolfSSL_Init().
=> ra-tls: check the return value of wolfSSL_Init

README.md
=> README.md: support pouch

README.md
=> README.md: support to run rune with pouch through configure annotations

rune/libenclave/check.go, rune/libenclave/configs/config.go, rune/libenclave/init.go, rune/libenclave/nitroenclaves/device_linux.go, rune/spec.go, rune/utils_linux.go
Enclave? It is a computational normal form. Any reasonable form is enclave, and Inclavare Containers will support it without hesitation.
=> add the initial support for AWS Nitro Enclaves

rune/dist/deb/debian/changelog, rune/dist/deb/debian/control, rune/dist/deb/debian/rules
=> rune/dist/deb: drop unnecessary dependency

README.md, docs/running_rune_with_pouch_and_occlum.md
=> README: reflect wamr support in reference docker container

rune/dist/deb/debian/changelog, rune/dist/deb/debian/control, rune/dist/rpm/rune.spec, sgx-tools/dist/deb/debian/changelog, sgx-tools/dist/rpm/sgx-tools.spec
=> rune & sgx-tools: bump the versions of deb and rpm to 0.5.1

rune/libenclave/internal/runtime/pal/nitro_enclaves/Makefile, rune/libenclave/internal/runtime/pal/nitro_enclaves/README.md, rune/libenclave/internal/runtime/pal/nitro_enclaves/ne.c, rune/libenclave/internal/runtime/pal/nitro_enclaves/ne.h, rune/libenclave/internal/runtime/pal/nitro_enclaves/nitro_enclaves.h, rune/libenclave/internal/runtime/pal/nitro_enclaves/pal_ne.c, rune/libenclave/internal/runtime/pal/nitro_enclaves/pal_ne.h
Fixes: #345
Signed-off-by: Song Yang <songyang@linux.alibaba.com>
=> rune/libenclave/nitro_enclaves: add a base support for aws sample nitro enclave

.github/workflows/compile_check.yml, .github/workflows/repository_setup.yml, .github/workflows/rune_with_docker_and_crictl.yml
=> .github/workflows: add  some integration testing cases

README.md, docs/running_inclavare_containers_with_pouch_and_occlum.md
=> README.md: support pouch + pouchd + shim-rune + rune + enclave container images

ra-tls/Makefile, ra-tls/elv/ra-tls-client.c, ra-tls/patch/wolfssl.patch, ra-tls/ra-tls-server/lib/Makefile, ra-tls/sgx-ra-tls/Makefile, ra-tls/stub-enclave/Makefile
=> ra-tls: enable debug build by default

.github/workflows/build_and_push_crictl_image.yml, .github/workflows/build_and_push_wamr_image.yml, .github/workflows/crictl/10-mynet.conf, .github/workflows/crictl/99-loopback.conf, .github/workflows/crictl/Dockerfile, .github/workflows/crictl/Dockerfile-centos8.1, .github/workflows/crictl/crictl.yaml, .github/workflows/crictl/hello_world.c, .github/workflows/crictl/samples/clean.sh, .github/workflows/crictl/samples/dragonwell.yaml, .github/workflows/crictl/samples/golang.yaml, .github/workflows/crictl/samples/hello.yaml, .github/workflows/crictl/samples/jdk.yaml, .github/workflows/crictl/samples/pod.yaml, .github/workflows/crictl/samples/show.sh
=> .github/workflows: support build and push wamr and crictl images

README.md
=> README.md: document to declare that inclavare containers is added to the adopters list of containerd

.github/workflows/k8s_centos.yml
Only support run and test occlum-hello pod on centos right now, we will
support more test cases in the future.
=> .github/workflows: support k8s nightly build on centos

.gitignore
=> inclavare-containers: ignore gnu global files

.github/workflows/rune_centos_with_docker_and_crictl.yml, .github/workflows/rune_ubuntu_with_docker_and_crictl.yml
=> .github/workflow: support parallel jobs

.github/workflows/build_and_push_wamr_image.yml, .github/workflows/k8s_centos.yml, .github/workflows/repository_setup.yml, .github/workflows/rune_centos_with_docker_and_crictl.yml, .github/workflows/rune_ubuntu_with_docker_and_crictl.yml
centos/ubuntu jobs
Fixes: #393
=> .github/workflows: use make -j${coreNum} to replace make in rune

rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
=> rune/libenclave/skeleton: add check for stdout and stderr in  __pal_get_local_report

.github/workflows/rune_centos_with_docker_and_crictl.yml, .github/workflows/rune_ubuntu_with_docker_and_crictl.yml
=> .github/workflows: add remote/local attestation CI/CD on ubuntu and centos

inclavared/Makefile.wolfssl, inclavared/app.wolfssl/Makefile, inclavared/app.wolfssl/src/main.rs, inclavared/stub-enclave.wolfssl/Makefile
The subsequent connections from clients should work as expected.
Fixes: #398
Signed-off-by: Jia Zhang <Jia Zhang>
=> inclavared: fix subsequent tls client connection failures

README.md
=> README: add nightly build status badge

.github/workflows/nightly.yml
=> .github/workflows: add clean network environment step in nightly build

ra-tls/Makefile, ra-tls/elv/main.go, ra-tls/ra-tls-server/Makefile, ra-tls/ra-tls-server/go.mod, ra-tls/ra-tls-server/main.go, ra-tls/ra-tls-server/run.go
=> ra-tls: rename enclaved to inclavared

.github/workflows/commit_centos.yml, .github/workflows/commit_ubuntu.yml
=> .github/workflows: add Occlum bundle test

rune/libenclave/internal/runtime/pal/api_v1_linux.go, rune/libenclave/internal/runtime/pal/api_v2_linux.go, rune/libenclave/internal/runtime/pal/api_v3_linux.go
=> rune/libenclave/skeleton: reformat cgo codes

Makefile
=> Makefile: enhance error handling when processing each component

.github/workflows/commit_centos.yml, .github/workflows/commit_ubuntu.yml
=> .github/workflows: keep the test container when test fails

rune/libenclave/check.go
=> rune/libenclave: make mount aesmd socket configurable

.github/workflows/nightly.yml
=> .github/workflows: enhance nightly build

shim/README-zh_CN.md, shim/README.md, shim/conf/config.toml, shim/dist/deb/debian/postinst, shim/dist/rpm/shim-rune.spec
=> shim/dist && shim/conf : keep consistent with the /etc/inclavare-containers/config.toml configuration file in README.md

.github/workflows/nightly.yml
Signed-off-by: Shirong Hao <shirong@linux.alibaba.com
=> .github/workflows: clean the environment before nightly build

.github/workflows/commit_centos.yml, .github/workflows/commit_compile_check.yml, .github/workflows/commit_ubuntu.yml, .github/workflows/manually_repository_setup.yml, .github/workflows/manually_wamr_image.yml, .github/workflows/nightly.yml
=> .github/workflows: use make -j{CPU_NUM} to speed up checking each commit compile on github machines

.github/workflows/commit_centos.yml, .github/workflows/commit_ubuntu.yml, .github/workflows/docker/Dockerfile, .github/workflows/docker/Dockerfile-centos8.1, .github/workflows/docker/Dockerfile-occlum, .github/workflows/docker/Dockerfile-skeleton, .github/workflows/docker/Dockerfile-ubuntu18.04, .github/workflows/docker/samples/show.sh, .github/workflows/manually_centos_test_image.yml, .github/workflows/manually_ubuntu_test_image.yml
=> .github/workflows: add centos and ubuntu test images to eliminate Internet interference

.github/workflows/commit_crictl.yml, .github/workflows/commit_occlum.yml, .github/workflows/commit_skeleton.yml, .github/workflows/manually_repository_setup.yml, .github/workflows/manually_wamr_image.yml, .github/workflows/nightly.yml
=> .github/workflows: add SGX2 test support

sgx-tools/README.md
=> sgx-tools/README.md: add declaration that not support DCAP driver until now

docs/running_inclavare_containers_with_pouch_and_occlum.md
=> docs: add loglevel in pouch run command

.github/workflows/commit_occlum.yml
=> .github/workflows: add semicolon after the command

.github/workflows/nightly.yml
=> .github/workflows: workround occlum package dependency problem

inclavared/app.wolfssl/src/main.rs
=> inclavared: fix startup failure due to lack of tls socket

.github/workflows/commit_epm.yml
=> .github/workflows: add epm testing support

.github/workflows/commit_epm.yml, epm/README.md, epm/cmd/epm/app/options/options.go, epm/conf/config.toml, epm/config/config_test.go
=> epm: unify epm configuration path about epm.db and config.toml

.github/workflows/nightly-centos-sgx1.yml, .github/workflows/nightly-ubuntu-sgx1.yml
=> .github/workflows: add Kubernetes nightly job on Ubuntu OS

README.md
=> README: add nightly centos and ubuntu status badge

README.md
=> README.md: simplify the description of the installation location of all components

.github/workflows/nightly-ubuntu-sgx1.yml
.github/workflows: update the workflow of Nightly-Ubuntu-SGX1 to clean up remaining packages
=> .github/workflows: update the workflow of Nightly-Ubuntu-SGX1 

rune/libenclave/internal/runtime/pal/skeleton/README.md
=> rune/libenclave/skeleton: Add the usage document of kvmtool

epm/dist/deb/debian/changelog, epm/dist/rpm/epm.spec, shim/dist/deb/debian/changelog, shim/dist/rpm/shim-rune.spec
1. Fix the release date of shim and epm
2. Add the changelog of version 0.5.2 of shim and rune
=> epm&shim: add the changelog of version 0.5.2 of shim and rune

epm/README.md
=> epm/README.md: add epm desgin reference link into epm README.md

.github/workflows/commit_compile_check.yml, .github/workflows/commit_occlum.yml, .github/workflows/commit_skeleton.yml, .github/workflows/manually_repository_setup.yml
=> .github/workflows: add occlum package in repo and touch .pb.go prior to build rune

CONTRIBUTING.md
=> CONTRIBUTING.md: explicitly document writing CI/CD

.github/workflows/commit_shelter.yml
=> .github/workflows: fix shelter test error

rune/libenclave/epm/epm.go, rune/libenclave/internal/runtime/pal/nitro_enclaves/README.md
=> Fix the typo encalvae

docs/running_inclavare_containers_with_pouch_and_occlum.md, rune/README.md
=> docs: add OCCLUM_RELEASE_ENCLAVE env to explicitly set enclave mode

.github/workflows/commit_compile_check.yml, .github/workflows/commit_epm.yml, .github/workflows/commit_occlum.yml, .github/workflows/commit_skeleton.yml
=> CI/CD: touch .pb.go in vendor directories

.github/workflows/nightly-centos-sgx1.yml, .github/workflows/nightly-ubuntu-sgx1.yml
=> CI/CD: update occlum version to 0.19.0 when nightly build

rune/libenclave/intelsgx/preload/device_linux.go
=> rune: preload libsgx_epid.so

rune/main.go
=> rune/cli: adjust rune command according to lexicographic order

.github/workflows/commit_skeleton.yml
=> CI/CD: fix the bug of failing to check the state of container for remote attestation testing

rune/libenclave/internal/runtime/pal/skeleton/Makefile, rune/libenclave/internal/runtime/pal/skeleton/README.md, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton-v3.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c, rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.h, rune/libenclave/internal/runtime/pal/skeleton/running_skeleton_with_tls_server.md, rune/libenclave/internal/runtime/pal/skeleton/tls-server.c, rune/libenclave/internal/runtime/pal/skeleton/tls-server.h
=> rune/libenclave/skeleton: interactive with ra-tls-server

.github/workflows/commit_epm.yml, epm/pkg/epm/enclave-cache-pool/enclavepool/enclave-cache.go, epm/pkg/epm/epm.go, epm/pkg/epm/interface.go, rune/libenclave/epm/cmsg.go, rune/libenclave/epm/epm.go, rune/libenclave/internal/runtime/pal/pal.go, rune/libenclave/internal/runtime/pal/pal_linux.go, rune/libenclave/internal/runtime/pal/skeleton/README.md
1. Support subtype to distiguish the same software with different version in  enclave runtime.
2. Fix an occasional crash when epm is started.
3. Support epm function impilicitly.
=> epm: add subtype function, support epm impilicitly and fix a bug

ra-tls/ra-tls-server/run.go
=> ra-tls: fix the bind address already in use problem

.github/workflows/commit_shelter.yml
=> CI/CD: add git proxy to speed up

rune/libenclave/internal/runtime/pal/skeleton/liberpal-skeleton.c
=> rune/libenclave/skeleton: fix the bug of the inaccurate wait_timeout args

ra-tls/Makefile, ra-tls/patch/wolfssl.patch, ra-tls/sgx-ra-tls/ra-challenger.c, ra-tls/sgx-ra-tls/ra-challenger_private.h, shelter/remoteattestation/ra-challenger.c, shelter/remoteattestation/ra-challenger_private.h
=> ra-tls: rebase ra-tls sample code with the latest stable wolfssl

.github/workflows/commit_epm.yml, .github/workflows/commit_occlum.yml, .github/workflows/commit_skeleton.yml, rune/README.md, rune/libenclave/internal/runtime/pal/skeleton/README.md
sync up with https://github.com/alibaba/inclavare-containers/commit/4c61ac439a99fb11a881ffcbea1df3c9ff12bd29.
=> rune/README.md && skeleton/README.md && CI/CD: add enclave runtime logLevel configuration

hack/use-sbx-platform/0001-QVL-allow-to-use-SBX-platform.patch, hack/use-sbx-platform/README.md
=> hack/use-sbx-platform: support to verify the quote generated by SBX platforms

rune/libenclave/intelsgx/aesmd.go, rune/libenclave/intelsgx/arch.go, rune/libenclave/intelsgx/proto/aesm-service.pb.go, rune/libenclave/intelsgx/proto/aesm-service.proto
=> rune/libenclave/intelsgx: implement ecdsa support for core APIs

.github/workflows/commit_skeleton.yml
=> CI/CD: update sgx-tools testcases by add the quote type

.github/workflows/commit_skeleton.yml
=> CI/CD: revert the workround of skeleton failed problem

rune/libenclave/attestation/sgx/ias/ias.go, rune/libenclave/intelsgx/aesmd.go, rune/libenclave/intelsgx/arch.go
=> rune/libenclave/intelsgx && attestation: both support quote version 2 and version 3

shelter/mrenclaveverifycomand.go, shelter/racommand.go, shelter/remoteattestation/securitychannel.go, shelter/verification/Makefile, shelter/verification/mrenclave.go
Fixes: #497
Signed-off-by: zhiminghufighting <13764765163@163.com>
=> shelter: correct the typo "encalve" to "enclave"

ra-tls/ra-tls-server/lib/Makefile, rune/libenclave/intelsgx/preload/device_linux.go, rune/libenclave/internal/runtime/pal/skeleton/Makefile, rune/libenclave/internal/runtime/pal/skeleton/running_skeleton_with_tls_server.md
=> skeleton: integrate the latest stable wolfssl with DCAP support

rune/dist/deb/debian/changelog, rune/dist/rpm/rune.spec, sgx-tools/dist/deb/debian/changelog, sgx-tools/dist/rpm/sgx-tools.spec
=> rune & sgx-tools: bump the versions of deb and rpm to 0.6.0

epm/dist/deb/debian/changelog, epm/dist/rpm/epm.spec, shim/dist/deb/debian/changelog, shim/dist/rpm/shim-rune.spec
=> shim & epm: update the spec files of shim and epm

rune/libenclave/internal/runtime/pal/skeleton/running_skeleton_with_tls_server.md
=> skeleton/running_skeleton_with_tls_server.md: fix the url error

ra-tls/elv/ra-tls-client.c
=> ra-tls: typo fix for ra-tls-client

rune/libenclave/internal/runtime/pal/skeleton/running_skeleton_with_tls_server.md
=> rune/skeleton: integrate the latest ra-tls with local report attestation support

.github/workflows/docker/Dockerfile-centos8.1
=> CI/CD: add glibc static dependency needed by ra-tls

.github/workflows/docker/Dockerfile-ubuntu18.04
This reverts commit 0843dd4864c250c30afef998673a39fa45356315.
=> Revert "CI/CD: drop unnecessary soft link about sgx_attributes.h in"

sgx-tools/dist/rpm/sgx-tools.spec
=> sgx-tools/dist/rpm: fix a typo

rune/libenclave/internal/runtime/pal/skeleton/README.md
=> skeleton: document well the dependency about protobuf

Makefile, shelter/Makefile
=> shelter: added to the top Makefile

epm/pkg/metadata/metadata.go
=> epm: fix the nil pointer bug when getting the ancestor caches

.github/workflows/commit_skeleton_ex.yml
=> CI/CD: add docker tag for inclavare-dev and inclavare-test images in commit-skeleton-ex.

.github/workflows/manually_inclavare_dev_image.yml, tools/docker/Dockerfile-inclavare-dev-centos8.2, tools/docker/Dockerfile-inclavare-dev-ubuntu18.04
=> CI/CD: add inclavare containers development centos8.2 and ubuntu 18.04 docker images

docs/develop_and_deploy_hello_world_application_in_kubernetes_cluster.md
=> docs/k8s: update occlum version to 0.20.0

epm/dist/deb/debian/postinst, epm/dist/rpm/epm.spec
=> epm/dist/deb && rpm: add the mkdir /var/run/epm in the post install stage

.github/workflows/commit_compile_check.yml, .github/workflows/docker/Dockerfile-compile-check-centos8.2, .github/workflows/manually_compile_check_image.yml, .github/workflows/manually_wamr_image.yml, README.md, docs/create_a_confidential_computing_kubernetes_cluster_with_inclavare_containers.md, docs/develop_and_deploy_hello_world_application_in_kubernetes_cluster.md, rune/libenclave/internal/runtime/pal/skeleton/README.md, rune/libenclave/internal/runtime/pal/skeleton/running_skeleton_with_tls_server.md
=> docs && CI/CD: update CentOS 8.1 to centOS 8.2 and Occlum:0.20.0 to Occlum:0.21.0

.github/workflows/commit_skeleton.yml
=> CI/CD: only test ra in the SGX1 occlum ubuntu docker images

.github/workflows/commit_compile_check.yml, .github/workflows/docker/Dockerfile-compile-check-alinux2, .github/workflows/manually_compile_check_image.yml
=> CI/CD: support compile check on alinux2 system

.github/workflows/manually_inclavare_dev_image.yml, tools/docker/Dockerfile-inclavare-dev-alinux2, tools/docker/Dockerfile-inclavare-dev-centos8.2, tools/docker/Dockerfile-inclavare-dev-ubuntu18.04
=> tools/docker && CI/CD: add inclavare containers development  aliyun linux 2 docker images

enclave-tls/src/Makefile
=> enclave-tls: fix common dir to external in Makefile

.github/workflows/commit_epm.yml
=> CI/CD: add alinux2 commit epm test

.github/workflows/commit_skeleton.yml
=> CI/CD: add clean up jobs in commit skeleton test

.github/workflows/commit_skeleton.yml
=> CI/CD: add alinux2 commit skeleton test

.github/workflows/commit_occlum.yml
=> CI/CD: add alinux2 commit occlum test

hack/use-sbx-platform/README.md
=> hack/use-sbx-platform: add the steps for ubuntu

enclave-tls/src/tls_wrappers/wolfssl/negotiate.c, enclave-tls/src/tls_wrappers/wolfssl/un_negotiate.c
=> enclave-tls: fix evidence verification failure still work

enclave-tls/README.md, enclave-tls/samples/enclave-tls-client/client.c, enclave-tls/samples/enclave-tls-server/server.c, enclave-tls/src/tls_wrappers/wolfssl/negotiate.c
=> enclave-tls: enable mutual attestation

README.md
=> README.md: add the explaination and pronunciation about inclavare

enclave-tls/samples/enclave-tls-client/client.c, enclave-tls/samples/enclave-tls-server/server.c
=> enclave-tls/samples: fix return value error

.github/workflows/commit_enclave_tls.yml, tools/docker/Dockerfile-inclavare-dev-alinux2, tools/docker/Dockerfile-inclavare-dev-centos8.2, tools/docker/Dockerfile-inclavare-dev-ubuntu18.04
=> CI/CD: add the testing for enclave-tls

enclave-tls/README.md
=> enclave-tls/README.md: fix the dependent package name error in ubuntu 18.04

enclave-tls/samples/enclave-tls-client/client.c, enclave-tls/samples/enclave-tls-server/server.c
=> enclave-tls: refactor occlum and sgx sdk build

tools/docker/Dockerfile-inclavare-dev-alinux2, tools/docker/Dockerfile-inclavare-dev-centos8.2, tools/docker/Dockerfile-inclavare-dev-ubuntu18.04
=> tools/docker: avoid repeated installation of the libsgx-uae-service package

enclave-tls/dist/rpm/enclave_tls.spec
=> enclave-tls/dist: add SGX SDK compile check in the rpm spec

enclave-tls/samples/enclave-tls-client/client.c, enclave-tls/samples/enclave-tls-server/server.c
=> enclave-tls: fix invalid response retrieved from occlum enclave-tls server

enclave-tls/src/Makefile, enclave-tls/src/external/wolfssl/Makefile
=> enclave-tls: change the install mod of head files to read-only

.github/actions/generate-random-port/action.yml, .github/actions/generate-random-port/generate_port.sh, .github/workflows/pr_shelter.yml
=> CI/CD: add test for shelter with enclave-tls-server

enclave-tls/README.md, enclave-tls/rules/sgx_env.mk, enclave-tls/src/external/wolfssl/Makefile
=> enclave-tls: introduce LVI mitigations by default

.github/workflows/pr_enclave_tls.yml
=> workflows/pr_enclave_tls: support to generate port dynamically

hack/no-sgx-flc/README.md, hack/no-sgx-flc/Workaround-the-conflict-between-isgx-out-of-tree-and.patch
=> hack/no-sgx-flc: provide the info about the workaround for isgx driver

shelter/README.md
=> shelter: employ Intel PCCS for local verification

rune/libenclave/internal/runtime/pal/skeleton/README.md
=> skeleton/README.md: fix the URL error of intergrating skeleton with tls server

.github/workflows/pr_enclave_tls.yml, .github/workflows/pr_epm.yml, .github/workflows/pr_shelter.yml, .github/workflows/pr_skeleton.yml
=> CI/CD: add SGX and DCAP versions both in the centos and ubuntu pr tests

shelter/dist/rpm/shelter.spec
=> CI/CD: build and install shelter rpm failed

shelter/dist/deb/debian/changelog, shelter/dist/deb/debian/control
=> CI/CD: build and install shelter deb package failed

shelter/README.md
=> shelter/README.md: minor fixes

rune/libenclave/internal/runtime/pal/skeleton/intergrate_skeleton_with_enclave_tls.md
=> skeleton/intergrate_skeleton_with_enclave_tls.md: add shelter as an enclave tls client support

enclave-tls/rules/build_env.mk
Signed-off-by: YiLin.Li <YiLin.Li@linux.alibaba.com>
=> enclave-tls: fix PIC => not found

.github/workflows/pr_skeleton.yml
=> CI/CD: fix a typo

enclave-tls/src/enclave_quotes/nullquote/main.c, enclave-tls/src/enclave_quotes/nullquote/verify_evidence.c, enclave-tls/src/enclave_quotes/sgx-ecdsa/main.c, enclave-tls/src/enclave_quotes/sgx-ecdsa/verify_evidence.c, enclave-tls/src/enclave_quotes/sgx-la/main.c, enclave-tls/src/enclave_quotes/sgx-la/verify_evidence.c, enclave-tls/src/include/enclave-tls/enclave_quote.h, enclave-tls/src/include/enclave-tls/tls_wrapper.h, enclave-tls/src/tls_wrappers/api/tls_wrapper_verify_certificate_extension.c, enclave-tls/src/tls_wrappers/nulltls/negotiate.c, enclave-tls/src/tls_wrappers/wolfssl/un_negotiate.c
Fixes: #868
Signed-off-by: Ruoyu.Ying <ruoyu.ying@intel.com>
=> Fix missing hash verification in sgx-ecdsa and sgx-la

enclave-tls/README.md, enclave-tls/samples/enclave-tls-client/client.c, enclave-tls/samples/enclave-tls-server/server.c
Fixes: #909
Signed-off-by: Ruoyu.Ying <ruoyu.ying@intel.com>
Add the help options according to README
=> enclave-tls/samples: provide --help/-h option to show the usage

.github/workflows/nightly-aliyunlinux-sgx2.yml, .github/workflows/nightly-centos-sgx1.yml, .github/workflows/nightly-ubuntu-sgx1.yml
=> cicd: set retry flags to wget command when downloading flannel yaml file

.github/workflows/nightly-aliyunlinux-sgx2.yml
=> CI/CD: change alinuxlinux to Alibaba Cloud Linux2

README.md
=> README: add nightly alinux2 and SGX2 status badge

shelter/README.md
=> shelter: change README for some code logical change.

enclave-tls/rules/sgx_env.mk, enclave-tls/rules/sgx_rules.mk, enclave-tls/src/Makefile, enclave-tls/src/crypto_wrappers/wolfcrypt/gen_cert.c, enclave-tls/src/enclave_quotes/Makefile, enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/Makefile, enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/cleanup.c, enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/collect_evidence.c, enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/ecalls.c, enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/init.c, enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/main.c, enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/ocalls.c, enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/pre_init.c, enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/quote_generation.h, enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/sgx_ecdsa.h, enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/sgx_ecdsa_qve.edl, enclave-tls/src/enclave_quotes/sgx-ecdsa-qve/verify_evidence.c, enclave-tls/src/enclave_quotes/sgx-ecdsa/collect_evidence.c, enclave-tls/src/enclave_quotes/sgx-ecdsa/verify_evidence.c, enclave-tls/src/external/wolfssl/patch/wolfssl.patch, enclave-tls/src/sgx/Makefile, enclave-tls/src/tls_wrappers/wolfssl-sgx/wolfssl_sgx.edl, enclave-tls/src/tls_wrappers/wolfssl/oid.c, enclave-tls/src/tls_wrappers/wolfssl/un_negotiate.c, enclave-tls/src/tls_wrappers/wolfssl/wolfssl.h
=> enclave-tls: add QvE support in ECDSA verification

shelter/remoteattestation/ratlsclient.c
=> shelter: fix output information

.github/workflows/docker/Dockerfile-compilation-testing-alinux2, .github/workflows/docker/Dockerfile-compilation-testing-centos8.2, .github/workflows/docker/Dockerfile-compilation-testing-ubuntu18.04, .github/workflows/pr_basic_compilation_check.yml, Makefile, inclavared/Makefile
Add inclavared to stable_components, participate in compilation
with the entire project.
Fixes: #957
=> inclavared: Add inclavared to stable_components

shelter/racommand.go
=> shelter: change --mutual value to --mutual

enclave-tls/rules/build_env.mk
=> enclave-tls: install samples into /usr/share/enclave-tls/samples

enclave-tls/samples/enclave-tls-client/client.c, enclave-tls/samples/enclave-tls-server/server.c
=> enclave-tls: add to handle for failing to load sgx stub enclave

enclave-tls/samples/enclave-tls-client/Makefile, enclave-tls/samples/enclave-tls-server/Makefile, enclave-tls/samples/sgx-stub-enclave/Makefile
=> enclave-tls: fix make uninstall error

enclave-tls/rules/sgx_rules.mk, enclave-tls/samples/sgx-stub-enclave/Makefile
=> enclave-tls: install sgx_stub_enclave.signed.so into Build_Bindir when make SGX=1

enclave-tls/src/tls_wrappers/wolfssl-sgx/init.c
=> enclave-tls: sanity check for the result of ecall into wolfssl init

enclave-tls/README.md, enclave-tls/docs/run_enclave_tls_with_occlum.md
=> enclave-tls/docs: refresh docs

shelter/racommand.go, shelter/remoteattestation/ratlsclient.c, shelter/remoteattestation/securitychannel.go, shelter/utils/manageprotocol.go
=> inclavared: sanity check the validation of request from shelter

enclave-tls/dist/rpm/enclave_tls.spec
=> enclave-tls/dist: add the postun rules in the rpm spec

tools/docker/Dockerfile-inclavare-dev-alinux2, tools/docker/Dockerfile-inclavare-dev-centos8.2, tools/docker/Dockerfile-inclavare-dev-ubuntu18.04
=> tools/docker: support rust compilation environment

inclavared/app/src/main.rs
=> inclavared: cleanup resources after tls handshake fails

.github/workflows/pr_enclave_tls.yml
=> workflows/pr_enclave_tls: update samples install path

inclavared/app/src/main.rs
inclavared: use only one enclave for all connections
=> inclavared: use only one enclave for all connections

.github/workflows/pr_shelter.yml
=> CICD: need to change enclave-tls default path in shelter cicd yml

enclave-tls/Makefile
=> enclave-tls: make uninstall should uninstall /usr/share/enclave-tls

.github/workflows/pr_shelter.yml
=> CI/CD: install shelter in /usr/local/bin

enclave-tls/samples/enclave-tls-client/Makefile, enclave-tls/samples/enclave-tls-server/Makefile, enclave-tls/src/Makefile
=> enclave-tls: uninstall libwolfssl*.so when make SGX=1

enclave-tls/docs/run_inclavared_and_shelter_with_enclave_tls.md
=> enclave-tls/docs: add the guide to run inclavared and shelter with enclave-tls

.github/workflows/pr_enclave_tls.yml
=> workflows/pr_enclave_tls: fix CI/CD failure due to the lack of -v enclave quote type

Makefile
=> enclave-tls: add enclave-tls as the stable component in top Makefile

epm/dist/deb/debian/changelog, epm/dist/rpm/epm.spec, shim/dist/deb/debian/changelog, shim/dist/rpm/shim-rune.spec
=> epm & shim: update spec files of epm and shim

.github/workflows/nightly-centos-sgx1.yml, .github/workflows/nightly-ubuntu-sgx1.yml
=> CI/CD: avoid building enclave-tls package in the nightly SGX1 test

README.md
=> README: add description about Enclave Attestation Architecture

README.md
=> README: add development docker images support and usage guide

inclavared/README.md
inclavared: add third party dependencies to readme
=> inclavared: add third party dependencies to readme

shim/README.md
=> shim-rune: add third party dependencies to readme file

.github/workflows/pr_enclave_tls.yml, .github/workflows/pr_shelter.yml
=> CI/CD: add test for openssl TLS Wrapper and Crypto Wrapper

shelter/README.md
=> Shelter: need to add third party depends on in README

rune/libenclave/internal/runtime/pal/spec.md
Signed-off-by: LiFeng <lifeng68@huawei.com>
=> pal spec: fix typo

enclave-tls/src/verifiers/sgx-ecdsa/verify_evidence.c
=> sgx-ecdsa: support to dump hash in quote

enclave-tls/rules/instance.mk, enclave-tls/rules/openssl_env.mk, enclave-tls/rules/openssl_rules.mk, enclave-tls/samples/sgx-stub-enclave/Makefile, enclave-tls/src/Makefile, enclave-tls/src/crypto_wrappers/Makefile, enclave-tls/src/crypto_wrappers/openssl/Makefile, enclave-tls/src/crypto_wrappers/openssl/cleanup.c, enclave-tls/src/crypto_wrappers/openssl/gen_cert.c, enclave-tls/src/crypto_wrappers/openssl/gen_privkey.c, enclave-tls/src/crypto_wrappers/openssl/gen_pubkey_hash.c, enclave-tls/src/crypto_wrappers/openssl/init.c, enclave-tls/src/crypto_wrappers/openssl/main.c, enclave-tls/src/crypto_wrappers/openssl/openssl.h, enclave-tls/src/crypto_wrappers/openssl/pre_init.c, enclave-tls/src/include/enclave-tls/err.h, enclave-tls/src/tls_wrappers/openssl/Makefile, enclave-tls/src/tls_wrappers/openssl/cleanup.c, enclave-tls/src/tls_wrappers/openssl/init.c, enclave-tls/src/tls_wrappers/openssl/main.c, enclave-tls/src/tls_wrappers/openssl/negotiate.c, enclave-tls/src/tls_wrappers/openssl/openssl.h, enclave-tls/src/tls_wrappers/openssl/pre_init.c, enclave-tls/src/tls_wrappers/openssl/receive.c, enclave-tls/src/tls_wrappers/openssl/transmit.c, enclave-tls/src/tls_wrappers/openssl/un_negotiate.c, enclave-tls/src/tls_wrappers/openssl/use_cert.c, enclave-tls/src/tls_wrappers/openssl/use_privkey.c
=> enclave-tls: add openssl tls instance

enclave-tls/samples/enclave-tls-server/server.c
Each enclave_tls_negotiate() call will assign a value to the ssl
field in the tls handle. This value is generally the data allocated
by SSL_new(). After multiple calls, the previously allocated ssl
will be leaked because it is overwritten by the later value. Use
a new tls handle for each handshake to solve this issue.
=> enclave-tls: Fix memory leak in enclave-tls-server

.github/workflows/pr_enclave_tls.yml, .github/workflows/pr_epm.yml, .github/workflows/pr_shelter.yml, .github/workflows/pr_skeleton.yml
=> workflows: add retry action when install dependency

enclave-tls/README.md, enclave-tls/samples/enclave-tls-client/client.c, enclave-tls/samples/enclave-tls-server/server.c
=> enclave-tls/samples: set debug flag by default on enclave creation

.github/workflows/pr_shelter.yml
=> pr_shelter: stop the workflow when build shelter failure

.github/workflows/pr_crictl.yml
The test result is in [link](https://github.com/haosanzi/inclavare-containers/runs/2882005661?check_suite_focus=true)
=> pr_crictl: enhance CI/CD error handling

.github/workflows/pr_enclave_tls.yml, .github/workflows/pr_shelter.yml
=> CI/CD: disable the enclave-tls openssl testing on alinux2

rune/README.md
=> rune/README: clarify the depenencies to libsgx-dcap-quote-verify-dev/libsgx-dcap-quote-verify-devel

.github/workflows/pr_shelter.yml
=> shelter: fix can not stat sgx_stub_enclave.signed.so error

.github/workflows/pr_epm.yml
=> pr_epm: enhance CI/CD error handling

rune/libenclave/internal/runtime/pal/skeleton/intergrate_skeleton_with_enclave_tls.md
=> skeleton: clean up the description about enclave-tls

enclave-tls/README.md
=> enclave-tls: license need to be changed in README file

tools/docker/Dockerfile-inclavare-dev-alinux2, tools/docker/Dockerfile-inclavare-dev-centos8.2, tools/docker/Dockerfile-inclavare-dev-ubuntu18.04
=> tools/docker: clean up dockerfiles

.github/workflows/nightly-aliyunlinux-sgx2.yml, .github/workflows/nightly-centos-sgx1.yml, .github/workflows/nightly-ubuntu-sgx1.yml, .github/workflows/pr_crictl.yml, .github/workflows/pr_enclave_tls.yml, .github/workflows/pr_epm.yml, .github/workflows/pr_occlum.yml, .github/workflows/pr_shelter.yml, .github/workflows/pr_skeleton.yml
=> CI/CD: redesign the lables of CICD machines

tools/docker/Dockerfile-inclavare-dev-alinux2, tools/docker/Dockerfile-inclavare-dev-centos8.2, tools/docker/Dockerfile-inclavare-dev-ubuntu18.04
Signed-off-by: Song Yang <songyang@linux.alibaba.com>
=> enclave-tls: Update base image to support cmake

.github/workflows/pr_crictl.yml, enclave-tls/dist/rpm/enclave_tls.filelist, enclave-tls/dist/rpm/enclave_tls.spec, enclave-tls/rules/build_env.mk
=> enclave-tls: fix an issue about making etls package failure

.github/workflows/pr_enclave_tls.yml
Signed-off-by: Song Yang <songyang@linux.alibaba.com>
=> enclave-tls: add cicd workflow for cmake

inclavared/Makefile, inclavared/dist/deb/build.sh, inclavared/dist/deb/debian/control, inclavared/dist/deb/debian/rules, inclavared/dist/rpm/inclavared.spec
Fixes: #1154
Signed-off-by: liangzhou121 <zhouliang121@126.com>
=> inclavared: fix make package failure

tools/docker/Dockerfile-inclavare-dev-alinux2
=> tools/docker: clean up aesm packages

.github/actions/make-packages/action.yml, .github/actions/start-docker-daemon/action.yml, .github/workflows/pr_epm.yml, .github/workflows/pr_skeleton.yml
=> CI/CD: fix docker daemon not start problem and add make package action

shelter/Makefile, shelter/dist/deb/debian/control, shelter/dist/rpm/shelter.spec
=> shelter: make package fails

rune/libenclave/agent.go
=> rune: fix docker exec invalid argument problem

.github/workflows/nightly-aliyunlinux-sgx2.yml, .github/workflows/nightly-centos-sgx1.yml, .github/workflows/nightly-ubuntu-sgx1.yml, .github/workflows/pr_occlum.yml
cicd: Install enable_rdfabase module automatically and use the local flannel yaml file instead of downloading directly.
Fixes: #1130
=> cicd: fix nightly cicd bugs

enclave-tls/src/tls_wrappers/openssl/cleanup.c
=> enclave-tls: shutdown SSL session when TLS cleanup

inclavared/dist/deb/debian/changelog, inclavared/dist/rpm/inclavared.spec
=> inclavared: bump the versions of deb and rpm to 0.6.2

shelter/dist/deb/debian/changelog, shelter/dist/rpm/shelter.spec
=> shelter: change version of deb and rpm to 0.6.2

shim/dist/deb/debian/changelog, shim/dist/rpm/shim-rune.spec
=> shim: release shim-0.6.2

.github/workflows/docker/Dockerfile-enclave-tls-runtime-testing-centos8.2, .github/workflows/docker/Dockerfile-enclave-tls-runtime-testing-ubuntu18.04, .github/workflows/manually_runtime_testing_image.yml, .github/workflows/pr_enclave_tls.yml, .github/workflows/pr_shelter.yml
=> CI/CD: add enclave-tls runtime test images

tools/docker/Dockerfile-inclavare-dev-alinux2, tools/docker/Dockerfile-inclavare-dev-centos8.2, tools/docker/Dockerfile-inclavare-dev-ubuntu18.04
=> tools/docker: update dev image to support cmake and vim

docs/build_and_run_encrypt_images.md
=> docs: add user guide to build and run encryption images

.github/workflows/pr_epm.yml
=> pr_epm: specify the version of dcap packages explicitly instead of installing the latest version from the repository

verdictd/app/Cargo.toml, verdictd/app/src/main.rs
=> verdictd: add a empty verdictd project

verdictd/app/Cargo.toml, verdictd/app/build.rs, verdictd/app/proto/keyprovider.proto, verdictd/app/src/crypto/aes256_cbc.rs, verdictd/app/src/crypto/mod.rs, verdictd/app/src/key_provider/annotation.rs, verdictd/app/src/key_provider/key_provider_grpc.rs, verdictd/app/src/key_provider/messages.rs, verdictd/app/src/key_provider/mod.rs, verdictd/app/src/main.rs
Add wrapKey and unwrapKey grpc service which will be used by ocicrypto and AA.
=> Add wrapKey and unWrapKey gRPC service.

.github/workflows/pr_basic_compilation_check.yml, verdictd/Makefile, verdictd/README.md, verdictd/app/build.rs
=> verdictd: add Makefile, readme and CI/CD compile testing item.

rbi/.gitignore, rbi/bios-256k/.gitignore, rbi/bios-256k/Dockerfile, rbi/bios-256k/build-bios.sh, rbi/bios-256k/build-docker-image.sh, rbi/bios-256k/readme.md, rbi/bios-256k/scripts/start.sh, rbi/rbi.sh, rbi/readme.md, rbi/readme_cn.md
rootfs, or so-called OS image reproducible build materials. Including
* RBCI's Dockerfile
* bios reproducible builder
* readme
=> Firmware bios-256k.bin's reproducible materials

rbi/kernel/Dockerfile, rbi/rbi.sh, rbi/readme.md
* Fix version info in Dockerfile
* Fix build scripts
=> Fix kernel build scripts and version infos

verdictd/README.md, verdictd/app/Cargo.toml, verdictd/app/build.rs, verdictd/app/src/main.rs
add verdictd's execution options such as listen address, etls's instances' type.
=> verdictd: add execution options.

verdictd/app/Cargo.toml, verdictd/app/src/attestation_agent/enclave_tls.rs, verdictd/app/src/attestation_agent/protocol.rs, verdictd/app/src/main.rs
=> verdictd: update AA handles to align with updated protocol

verdictd/app/Cargo.toml, verdictd/app/proto/keyprovider.proto, verdictd/app/src/key_provider/key_provider_grpc.rs, verdictd/app/src/main.rs
=> verdictd: verdictd's gRPC service can response skopeo wrap request successfully

verdictd/README.md, verdictd/app/src/policyEngine/opa/opaEngine.rs
OPA's cargo test can be executed successfully.
=> verdictd: add some opa input field type checking and some codes' optimization

.github/workflows/docker/Dockerfile-compilation-testing-centos8.2, .github/workflows/docker/Dockerfile-compilation-testing-ubuntu18.04
=> tools/docker: update build image to support cmake

verdictd/README.md, verdictd/app/build.rs, verdictd/app/proto/configureprovider.proto, verdictd/app/src/configure_provider/mod.rs, verdictd/app/src/configure_provider/provider.rs, verdictd/app/src/main.rs
=> verdictd: add configuration interface

verdictd/Makefile
=> verdictd: switch dependency to rats-tls

rbi/kernel/check-integrity.sh, rbi/rbi.sh
This pr aims to provide a simple entrance of 'build' and 'integrity check' for coming in-toto pipeline
add kernel building func in rbi.sh
add integrity checker for kernel
Signed-off-by: Xynnn_ <ding.ma@linux.alibaba.com>
=> rbi: add in-toto support for kernel rb

.github/workflows/pr_basic_compilation_check.yml, verdict/Makefile
=> verdict: add makefile and enable CI/CD compile testing

rats-tls/samples/enclave-tls-client/client.c, rats-tls/samples/enclave-tls-server/server.c, rats-tls/samples/sgx-stub-enclave/sgx_stub_ecall.c, rats-tls/src/CMakeLists.txt, rats-tls/src/api/enclave_tls_callback.c, rats-tls/src/include/enclave-tls/api.h, rats-tls/src/include/internal/core.h, rats-tls/src/tls_wrappers/openssl/un_negotiate.c
=> rats-tls: add user callback for OPA

.github/workflows/pr_occlum.yml
=> pr_occlum: use start-docker-daemon action to start docker

verdictd/app/src/enclave_tls/ffi.rs, verdictd/app/src/enclave_tls/mod.rs
=> verdictd: add enclave-tls user callback function

rune/dist/deb/debian/changelog, rune/dist/rpm/rune.spec, sgx-tools/dist/deb/debian/changelog, sgx-tools/dist/rpm/sgx-tools.spec, shim/dist/deb/debian/changelog, shim/dist/rpm/shim-rune.spec
=> rune && shim && sgx-tools: bump the version of deb and rpm to 0.6.3

rats-tls/CMakeLists.txt, rats-tls/src/attesters/internal/etls_enclave_attester_load_all.c, rats-tls/src/attesters/nullattester/CMakeLists.txt, rats-tls/src/attesters/sgx-ecdsa/CMakeLists.txt, rats-tls/src/crypto_wrappers/internal/etls_crypto_wrapper_load_all.c, rats-tls/src/crypto_wrappers/nullcrypto/CMakeLists.txt, rats-tls/src/crypto_wrappers/openssl/CMakeLists.txt, rats-tls/src/tls_wrappers/internal/etls_tls_wrapper_load_all.c, rats-tls/src/tls_wrappers/nulltls/CMakeLists.txt, rats-tls/src/tls_wrappers/openssl/CMakeLists.txt, rats-tls/src/verifiers/internal/etls_enclave_verifier_load_all.c, rats-tls/src/verifiers/nullverifier/CMakeLists.txt, rats-tls/src/verifiers/sgx-ecdsa-qve/CMakeLists.txt, rats-tls/src/verifiers/sgx-ecdsa/CMakeLists.txt
=> Use versioned filenames for tls wrapper and quote instances

enclave-tls/rules/build_env.mk
=> enclave-tls: solve a potential issue that -ldl -lc can't be found

.github/workflows/pr_eaa.yml
=> eaa: add CI/CD testing

rats-tls/samples/rats-tls-server/server.c, rats-tls/src/api/rats_tls_init.c, rats-tls/src/api/rats_tls_negotiate.c
=> rats-tls: introduce the new concept "session" in enclave tls API

.github/workflows/pr_eaa.yml
=> eaa: add verdict CI/CD testing

inclavared/app/Cargo.toml
=> inclavared: add stormgbs <stormgbs@gmail.com> back to authors list

.github/workflows/docker/Dockerfile-compilation-testing-centos8.2, .github/workflows/docker/Dockerfile-compilation-testing-ubuntu18.04
=> CI/CD: update sgx stack version to 2.14 in compilation test images

inclavare-containers.io/layouts/partials/footer.html
=> website: add Linux Foundation footer

eaa/verdict/Cargo.toml, eaa/verdict/src/main.rs, eaa/verdictd/Cargo.toml, eaa/verdictd/src/attestation_agent/protocol.rs, eaa/verdictd/src/attestation_agent/rats_tls.rs, eaa/verdictd/src/configure_provider/provider.rs, eaa/verdictd/src/key_manager/directory_key_manager.rs, eaa/verdictd/src/key_provider/key_provider_grpc.rs, eaa/verdictd/src/main.rs, eaa/verdictd/src/policy_engine/opa/opa_engine.rs, eaa/verdictd/src/rats_tls/mod.rs
=> eaa: use env_log as verdictd & verdict info output mechanism

README.md
=> README: add CII best practices badge

tools/docker/Dockerfile-inclavare-dev-ubuntu18.04
=> tool: add skopeo, crictl into dev dockerfile

tools/docker/Dockerfile-inclavare-dev-centos8.2
=> tools/docker: add skopeo, crictl into centos 8.2 dev dockerfile

.github/workflows/pr_basic_compilation_check.yml
=> docker: fix goproxy certificate expired error

eaa/verdictd/src/rats_tls/ffi.rs
=> eaa: verdictd support tdx verifier/attester

rats-tls/src/include/rats-tls/api.h, rats-tls/src/tls_wrappers/openssl/CMakeLists.txt, rats-tls/src/tls_wrappers/openssl/init.c, rats-tls/src/tls_wrappers/openssl/openssl.h, rats-tls/src/tls_wrappers/openssl/un_negotiate.c, rats-tls/src/tls_wrappers/openssl/use_cert.c, rats-tls/src/tls_wrappers/openssl/x509_openssl10x.c
=> rats-tls: compatible with openssl 1.0.x

README.md
=> README: move FOSSA badge state to the beginning of readme

rats-tls/src/CMakeLists.txt
Fixes: #1456
Signed-off-by: Zhiming Hu <zhiming.hu@intel.com>
=> rats-tls: run rats-tls-server failed

.github/workflows/pr_eaa.yml
=> eaa: Fix CICD failure

.clang-format
=> Recover .clang-format

rats-tls/CMakeLists.txt, rats-tls/samples/sgx-stub-enclave/CMakeLists.txt, rats-tls/src/CMakeLists.txt, rats-tls/src/attesters/nullattester/CMakeLists.txt, rats-tls/src/attesters/sgx-ecdsa/CMakeLists.txt, rats-tls/src/attesters/sgx-la/CMakeLists.txt, rats-tls/src/crypto_wrappers/nullcrypto/CMakeLists.txt, rats-tls/src/crypto_wrappers/openssl/CMakeLists.txt, rats-tls/src/external/sgx-ssl/CMakeLists.txt, rats-tls/src/sgx/trust/CMakeLists.txt, rats-tls/src/tls_wrappers/nulltls/CMakeLists.txt, rats-tls/src/tls_wrappers/openssl/CMakeLists.txt, rats-tls/src/verifiers/nullverifier/CMakeLists.txt, rats-tls/src/verifiers/sgx-ecdsa-qve/CMakeLists.txt, rats-tls/src/verifiers/sgx-ecdsa/CMakeLists.txt, rats-tls/src/verifiers/sgx-la/CMakeLists.txt
=> rats-tls: fatal error: openssl/opensslv.h: No such file or directory

rats-tls/samples/rats-tls-client/client.c, rats-tls/samples/rats-tls-server/server.c, rats-tls/samples/sgx-stub-enclave/sgx_stub_ecall.c
=> rats-tls: change "Rats TLS" in the banner info to "RATS-TLS"

rats-tls/cmake/SGXSSL.cmake
=> rats-tls: in sgx mode build will failed without libsgx-tsgx-ssl.a

.github/workflows/pr_epm.yml, README.md, docs/create_a_confidential_computing_kubernetes_cluster_with_inclavare_containers.md, enclave-tls/README.md, rats-tls/README.md, rune/README.md, tools/docker/Dockerfile-inclavare-dev-centos8.2, tools/docker/Dockerfile-inclavare-dev-ubuntu18.04
=> CI/CD && README: update sgx stack version to 2.14

rats-tls/src/core/cpu.c, rats-tls/src/include/edl/rtls_syscalls.edl
=> rats-tls: fix code style

eaa/verdictd/README.md
Update readme file according to verdictd's latest implementation
=> EAA|Verdictd: update readme

rune/Makefile, rune/go.mod, rune/go.sum, rune/libenclave/container_linux.go, rune/libenclave/rootfs_linux.go, rune/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpu.go, rune/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/hugetlb.go, rune/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/common.go, rune/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/dbus.go, rune/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/v1.go, rune/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/v2.go, rune/vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go, rune/vendor/github.com/opencontainers/runc/libcontainer/container_linux.go, rune/vendor/github.com/opencontainers/runc/libcontainer/message_linux.go, rune/vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c, rune/vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go, rune/vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_linux.go, rune/vendor/modules.txt
Upgrade github.com/opencontainers/runc to version 1.0.3
to fix GHSA-v95c-p5hm-xq8f issue.
=> rune: fix GHSA-v95c-p5hm-xq8f issue

.github/workflows/pr_verdictd.yml, verdictd/cmd/verdict/readme.md, verdictd/cmd/verdict/src/main.rs, verdictd/cmd/verdict/src/opa.rs, verdictd/proto/configureprovider.proto, verdictd/src/configure_provider/provider.rs, verdictd/src/main.rs, verdictd/src/policy_engine/opa/opa_engine.go, verdictd/src/policy_engine/opa/opa_engine.rs, verdictd/src/rats_tls/mod.rs
=> Verdictd: Enhance OPA interfaces

rats-tls/src/verifiers/api/enclave_verifier_register.c, rats-tls/src/verifiers/sgx-ecdsa-qve/main.c, rats-tls/src/verifiers/sgx-ecdsa/main.c, rats-tls/src/verifiers/sgx-la/main.c
Fixes: #1520
Signed-off-by: HuZhiming <zhiming.hu@intel.com>
=> ra-tls: fix verifier instance lost in verifier register

.github/actions/make-packages/action.yml, .github/workflows/pr_verdictd.yml, Makefile, verdictd/dist/deb/debian/rules, verdictd/dist/rpm/verdictd.spec.in
=> verdictd: switch cicd to make package cmd

.github/workflows/nightly-centos-sgx1.yml, .github/workflows/nightly-ubuntu-sgx1.yml
=> nightly: fix make packages error

.github/actions/make-packages/action.yml, .github/workflows/pr_verdictd.yml, tools/docker/Dockerfile-inclavare-dev-alinux2, tools/docker/Dockerfile-inclavare-dev-centos8.2, tools/docker/Dockerfile-inclavare-dev-ubuntu18.04
Also update corresponding CICD testing
=> dockerfile: add opa dependencies

rats-tls/src/CMakeLists.txt, rats-tls/src/attesters/nullattester/CMakeLists.txt, rats-tls/src/attesters/sgx-ecdsa/CMakeLists.txt, rats-tls/src/attesters/sgx-la/CMakeLists.txt, rats-tls/src/crypto_wrappers/nullcrypto/CMakeLists.txt, rats-tls/src/crypto_wrappers/openssl/CMakeLists.txt, rats-tls/src/sgx/trust/CMakeLists.txt, rats-tls/src/sgx/untrust/CMakeLists.txt, rats-tls/src/tls_wrappers/nulltls/CMakeLists.txt, rats-tls/src/tls_wrappers/openssl/CMakeLists.txt, rats-tls/src/verifiers/nullverifier/CMakeLists.txt, rats-tls/src/verifiers/sgx-ecdsa-qve/CMakeLists.txt, rats-tls/src/verifiers/sgx-ecdsa/CMakeLists.txt, rats-tls/src/verifiers/sgx-la/CMakeLists.txt
=> rats-tls: support 'install' in sgx mode

rats-tls/samples/sgx-stub-enclave/sgx_stub_ecall.c
=> rats-tls: SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca

verdictd/src/attestation_agent/protocol.rs, verdictd/src/attestation_agent/rats_tls.rs
=> verdictd: support EAA echo command

verdictd/cmd/verdict/readme.md, verdictd/src/policy_engine/opa/opa_engine.rs
Fix policy check failure when debug with SGX rats-tls
=> verdictd: update OPA default policy

rats-tls/README.md, rats-tls/samples/rats-tls-client/client.c, rats-tls/samples/sgx-stub-enclave/sgx_stub.edl, rats-tls/samples/sgx-stub-enclave/sgx_stub_ecall.c
=> rats-tls: add support to connect verdictd based on EAA echo command

rats-tls/CMakeLists.txt, rats-tls/MAINTAINERS, rats-tls/dist/Makefile, rats-tls/dist/rpm/rats-tls-filelist, rats-tls/dist/rpm/rats-tls-sgx-filelist, rats-tls/dist/rpm/rats_tls.spec.in
=> rats-tls: divide rpm package into sub-packages

hack/no-sgx-flc/README.md, hack/no-sgx-flc/linux-kernel-5.13-x86-sgx-Support-the-machines-without-FLC-support.patch
=> hack: add no sgx flc support for linux 5.13

.github/workflows/manually_compilation_testing_image.yml, .github/workflows/pr_basic_compilation_check.yml, .github/workflows/pr_enclave_tls.yml, .github/workflows/pr_epm.yml, .github/workflows/pr_occlum.yml, .github/workflows/pr_rats_tls.yml, .github/workflows/pr_shelter.yml, .github/workflows/pr_skeleton.yml, .github/workflows/pr_verdictd.yml, README.md, docs/create_a_confidential_computing_kubernetes_cluster_with_inclavare_containers.md, docs/develop_and_deploy_hello_world_application_in_kubernetes_cluster.md, rune/README.md, rune/libenclave/internal/runtime/pal/nitro_enclaves/README.md, rune/libenclave/internal/runtime/pal/skeleton/README.md, rune/libenclave/internal/runtime/pal/skeleton/intergrate_skeleton_with_enclave_tls.md, sgx-tools/README.md
=> docs: remove centos8 related supporting
